### ISSUE TITLE
Only compiles on Linux?

### ISSUE THREAD

**Issue by digitalsanctum** [istio/ztunnel#1]
I tried compiling on mac m1 and no go because of linux only configuration present.

On Ubuntu I had to install `librust-clang-sys-dev` and `protobuf-compiler` packages to get things working there.

**Comment by howardjohn** [comment]
The ubuntu part - running off linux is not a priority for me personally but would accept PRs of course; it shouldn't be too hard to put things behind cfg guards

**Comment by keithmattix** [comment]
I added some stubs that just return err; if that would be useful, I can submit a PR

**Comment by stevenctl** [comment]
Allow the many developers using macs to contribute.

**Comment by ams0** [comment]
with this simple Dockerfile I could run `cargo build` fine:


```
FROM rust

RUN apt-get update && apt-get install libclang-dev  protobuf-compiler libprotobuf-dev -y &&  rm -rf /var/lib/apt/lists/*
```

**Comment by howardjohn** [comment]
We have a dockerfile built in to the repo. You can do `make shell` to enter it, or just any `make` commands like `make build`

**Comment by therealmitchconnors** [comment]
This might be the world's smallest violin, but I can't seem to get `make build` working on my M2 mac, even from within the container.  When linking boringssl, I get:

```
 /usr/bin/ld: /workspaces/ztunnel/out/rust/debug/deps/libboring_sys-39720c5b79a85c79.rlib: error adding symbols: file in wrong format
          collect2: error: ld returned 1 exit status
```

**Comment by howardjohn** [comment]
Should be fixed by https://github.com/istio/ztunnel/pull/139
