### ISSUE TITLE
Drop internal fork of h2

### ISSUE THREAD

**Issue by bleggett** [istio/ztunnel#1000]
Spun out of: https://github.com/istio/ztunnel/pull/998#pullrequestreview-2034609417

Before we can do this:

- https://github.com/hyperium/h2/pull/772 or equivalent has to merge in upstream.

**Comment by howardjohn** [comment]
PR merged so hopefully they tag a release. unfortunately you need a `patch` in cargo if not, unlike go

**Comment by bleggett** [comment]
woo, happy with the turnaround either way.
