### ISSUE TITLE
Suggestion: restructure project

### ISSUE THREAD

**Issue by digitalsanctum** [istio/ztunnel#101]
Given that there's going to be things like benches and integration tests, I suggest we refactor using cargo workspaces [1]. 

An example of it in practice can be found in the tokio project [2]. 

Albeit this project is not that large yet, this seems like something that should be done sooner rather than later?

[1] https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html
[2] https://github.com/tokio-rs/tokio/blob/master/Cargo.toml

**Comment by howardjohn** [comment]
I am not sure I see the benefit? Would we have a workspace with one Cargo.toml? Or multiple Cargo.toml? If so, what would be the split?

The one benefit I can clearly see is different deps for tests ,but doesn't dev-dependencies already solve that?

**Comment by stevenctl** [comment]
If this repo ever produces a different binary, or we want to expose some of our code as a library I would see value in switching. 

Is there evidence of difficulties switching late? I'd rather do it as needed.

**Comment by digitalsanctum** [comment]
@howardjohn The two main benefits are incremental compilation and organization. I'd propose just the conventional layout to start [1]. As @stevenctl alluded to, you could have an arbitrary number of libs and bins while sharing the same `Cargo.lock` and `target` directory.

Admittedly, it may be premature to adopt workspaces but I'd still propose the idiomatic project structure.

[1] https://doc.rust-lang.org/stable/cargo/guide/project-layout.html

**Comment by howardjohn** [comment]
I think we are following the conventional layout now, and sounds like this isn't a clear need for multi-crates yet. I think its fair to consider this done for now, and if we need to split crates we can do that as needed. Thanks for the help
