### ISSUE TITLE
Ztunnel should log on NACK

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#1077]
When we NACK, we do not log. NACK is a critical error, so we ought to log

**Comment by ilrudie** [comment]
@howardjohn, do you already have code for this?

**Comment by howardjohn** [comment]
nope, we collect the failures in L690 of src/xds/client.rs, I think we just need a reasonable log there

**Comment by ilrudie** [comment]
sounds, good. I'll take a look at knocking something out.
