### ISSUE TITLE
Develop certificate provider module that can reach out to Istiod CA over gRPC and fetch and rotate certificates

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#11]

**Comment by howardjohn** [comment]
The "fetching certs" part is done. Now we need something to cache them and rotate them.

What we want:

* In SecretManager, store a cache of certificates we own
* For each cert, at 50% of its lifetime, refresh it. See `secretcache.go` in agent for prior art here, although it can likely be a bit simpler here (I think we can just spawn a task with `sleep(TTL); refresh` or something)
* When a new workload on the node is discovered, pre-fetch its cert (if we don't have it yet)
* `SecretManager.fetch_certificate` uses the cache when possible.
* If we race on explicit fetch_certificate call and pre-fetch, we should only have 1 request to the CA and both await it; a CA request has high cost

**Comment by stevenctl** [comment]
zTunnel can request cert on behalf of workload

Certs are pre-fetched on workload discovery

Certs are cached and re-used 

Certs in cache are automatically rotated

**Comment by SkyfireFrancisZ** [comment]
first PR merged o Fri 11/19

**Comment by SkyfireFrancisZ** [comment]
Split cache on discovery into separate issue, then mark this one done.
