### ISSUE TITLE
Optimize Read/Write syscalls

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#110]
Aside from TLS crypto overhead, most CPU time is spent on r/w syscalls.

Brain dump from my investigations so far...

When we switch from rustls to boringssl, we saw a 50% regression in perf. 

Some analysis of the R/W pattern

BoringSSL reads: read 5/26/5/8k. Each 5 read is the TLS record header, while the 26 is the H2 data frame header. the 8k is the data frame body.
BoringSSL writes: write 5/26/5/8k

Rustls reads: all 16k
Rustls writes: 31/8k/31/8k - this is H2 header then body repeated.

So Rustls is doing a full buffering on reads, but still writing header and frame in 2 writes. Boringssl is much worse; the TLS reads are reading the TLS record header and data separately which compounds with the writes being split as well. This tanks the performance.

---

https://github.com/istio/ztunnel/pull/109 dramatically improves this all around. With this, we see:

Both Reads and writes sometimes are 5/26/5/16k, but other times multiple 16k reads in a row. Not clear why. 

There is likely room for improvement here. 

---

Research notes:
SSL_read takes in a buffer, but that isn't used as the buffer for recv syscalls; instead it handles all that internally with a growing buffer and then memcpy's it into our buffer. I couldn't find anyway to influence this behavior

The small writes are because of rust code calling SSL_write with small data. This largely seems due to The h2 library: https://github.com/hyperium/h2/blob/294000c0745c64009151a1ab39978cd6f02dfd68/src/codec/framed_write.rs#L128 will make a `Chain` with the frame header and frame data, then call write()

https://github.com/hyperium/h2/blob/294000c0745c64009151a1ab39978cd6f02dfd68/src/codec/framed_write.rs#L181-L187 will only call poll_write_vectored if the writer supports it; the BoringSSL writer does not - and neither does any other TLS library in the ecosystem that I found. So we end up on the other path; chunk() returns only the frame header, it doesn't concat them.

So if we made a writer that implements poll_write_vectored by concating the bytes together, we may see some improvements.

---

stracing methodology:

```
strace -s 0 -ff -o cmd.strace -v -s 64 -x ./out/rust/release/ztunnel
cat cmd* | rg recv | hh '\\27\\3' recvfrom '= 5' sendto 8192 8214 '\\x17\\x03\\x03' 15360
cat cmd* | rg sendto | hh '\\27\\3' recvfrom '= 5' sendto 8192 8214 '\\x17\\x03\\x03' 15360
```

**Comment by Stevenjin8** [comment]
@howardjohn What did you run through your ztunnel? I see the `recvfrom(..., 5) = 5`, but my `sendto` calls all have at least 30 bytes and seem to correspond to one packet on the wire. By `write` calls do you mean calling `recv` and then writing the data to a buffer?

**Comment by howardjohn** [comment]
I believe this was all iperf so should be writing big chunks at a time

**Comment by Stevenjin8** [comment]
BoringSsl(?) tries to be very precise with `recv` calls. When it begins parsing a TLS record, it will always do it this way.

```
recvfrom(fd, "\x17\x03\x03\x00\x29", 5)
recvfrom(fd, "...", 41)
``

so it parses the record header and gets the length of the body. It them parses the exact number of bytes in the body (0x0029 = 41). sendto calls don't do this.
