### ISSUE TITLE
Issue trying ambient mode on an ipv4-only k8s cluster

### ISSUE THREAD

**Issue by aek-dsk** [istio/ztunnel#1131]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Trying ambient mode on the k8s cluster with ipv4 only results in a failing installation via Helm of ztunnel pods (crashing) producing the following error in the logs:

2024-06-04T10:35:38.591582Z	info	ztunnel	version: version.BuildInfo{Version:"909bf991d01edc4db51265bc633acfe303555ef5", GitRevision:"909bf991d01edc4db51265bc633acfe303555ef5", RustVersion:"1.77.2", BuildProfile:"release", BuildStatus:"Clean", GitTag:"1.22.0-beta.1-6-g909bf99", IstioVersion:"unknown"}	
2024-06-04T10:35:38.591778Z	info	ztunnel	running with config: proxy: true
dnsProxy: false
windowSize: 4194304
connectionWindowSize: 4194304
frameSize: 1048576
poolMaxStreamsPerConn: 100
poolUnusedReleaseTimeout:
  secs: 300
  nanos: 0
socks5Addr: null
adminAddr: 127.0.0.1:15000
statsAddr: '[::]:15020'
readinessAddr: '[::]:15021'
inboundAddr: '[::]:15008'
inboundPlaintextAddr: '[::]:15006'
outboundAddr: '[::]:15001'
dnsProxyAddr: 127.0.0.1:15053
network: ''
localNode: f74ac986-14da-431f-91b0-9bd7f0fdb6e8
proxyMode: Shared
localIp: 11.32.10.9
clusterId: Kubernetes
clusterDomain: cluster.local
caAddress: https://istiod.ccp-istio-system.svc:15012
caRootCert: !File ./var/run/secrets/istio/root-cert.pem
xdsAddress: https://istiod.ccp-istio-system.svc:15012
xdsRootCert: !File ./var/run/secrets/istio/root-cert.pem
secretTtl:
  secs: 86400
  nanos: 0
xdsOnDemand: false
fakeCa: false
selfTerminationDeadline:
  secs: 5
  nanos: 0
proxyMetadata:
  DNS_AUTO_ALLOCATE: 'false'
  ISTIO_VERSION: 1.22.0
  CLUSTER_ID: Kubernetes
  DNS_CAPTURE: 'false'
  ENABLE_HBONE: 'true'
  DNS_PROXY_ADDR: 127.0.0.1:15053
numWorkerThreads: 2
enableOriginalSource: null
proxyArgs: proxy ztunnel
dnsResolverCfg:
  domain: null
  search:
  - ccp-istio-system.svc.cluster.local
  - svc.cluster.local
  - cluster.local
  name_servers:
  - socket_addr: 10.100.192.2:53
    protocol: udp
    tls_dns_name: null
    trust_negative_responses: false
    bind_addr: null
  - socket_addr: 10.100.192.2:53
    protocol: tcp
    tls_dns_name: null
    trust_negative_responses: false
    bind_addr: null
dnsResolverOpts:
  ndots: 5
  timeout:
    secs: 5
    nanos: 0
  attempts: 2
  rotate: false
  check_names: true
  edns0: false
  validate: false
  ip_strategy: Ipv4thenIpv6
  cache_size: 32
  use_hosts_file: true
**Error: readiness server starts**

**Caused by:**
    **Address family not supported by protocol (os error 97)**
  positive_min_ttl: null
  negative_min_ttl: null
  positive_max_ttl: null
  negative_max_ttl: null
  num_concurrent_reqs: 2
  preserve_intermediates: true
  try_tcp_on_error: false
  server_ordering_strategy: QueryStatistics
  recursion_desired: true
  authentic_data: false
  shuffle_dns_servers: false
inpodEnabled: true
inpodUds: /var/run/ztunnel/ztunnel.sock
inpodPortReuse: true
inpodMark: 1337
	
2024-06-04T10:35:38.592025Z	debug	rustls::webpki::anchors	add_parsable_certificates processed 1 valid and 0 invalid certs	
2024-06-04T10:35:38.594727Z	info	readiness	Task 'proxy' complete (3.528422ms), still awaiting 1 tasks	
2024-06-04T10:35:38.594744Z	info	readiness	Task 'state manager' complete (3.547623ms), marking server ready

Expected behavior:
Successful installation of the istio ambient mode.

Happy to provide additional information if needed.

### Version

```Text
~$ istioctl version --istioNamespace=ccp-istio-system
2024-06-11T13:08:32.158200Z	error	klog	an error occurred forwarding 53952 -> 15014: error forwarding port 15014 to pod 0ae2ab77ab30cfa4ae893f2a017df61d7e66a43671d17381430a64820cfa5405, uid : network namespace for sandbox "0ae2ab77ab30cfa4ae893f2a017df61d7e66a43671d17381430a64820cfa5405" is closed
2024-06-11T13:08:32.158624Z	error	port forward failed: lost connection to pod
2 errors occurred:
	* error port-forwarding into ccp-istio-system.istiod-78fb865f7-6rcws: failure running port forward process: Get "http://localhost:53952//version": EOF
	* failure running port forward process: Get "http://localhost:53952//version": EOF


2024-06-11T13:08:32.306583Z	error	klog	an error occurred forwarding 53957 -> 15014: error forwarding port 15014 to pod 0ae2ab77ab30cfa4ae893f2a017df61d7e66a43671d17381430a64820cfa5405, uid : network namespace for sandbox "0ae2ab77ab30cfa4ae893f2a017df61d7e66a43671d17381430a64820cfa5405" is closed
2024-06-11T13:08:32.308146Z	error	port forward failed: lost connection to pod
1.22.0

without using "distroless" version:

~$ istioctl version --istioNamespace=ccp-istio-system
client version: 1.22.0
control plane version: 1.22.0
data plane version: 1.22.0 (65 proxies)

~$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.16+vmware.1
WARNING: version difference between client (1.29) and server (1.25) exceeds the supported minor version skew of +/-1
```

**Comment by howardjohn** [comment]
Is it easy to detect if they don't have ipv6 compiled in? if so we could just automate it

**Comment by bleggett** [comment]
> Is it easy to detect if they don't have ipv6 compiled in? if so we could just automate it

dunno, but that's an option yep.

**Comment by leosarra** [comment]
I don't know how easily we can reliably check if the IPv6 module is loaded.
If that cannot be done, we could expose the Kubernetes pod IPs field to the container.
If only IPv4 addresses are specified (single-stack ipv4 cluster), we use 0.0.0.0 as the unspecified address; otherwise, we use :: . Though, this would end up using 0.0.0.0 also for ipv4-only clusters where the ipv6 module is enabled.

**Comment by aek-dsk** [comment]
Thank you all for the responses.

IMHO: A back-compat flag configurable via Helm as a pragmatic solution would definitely work for me --> no need for over-engineering if that would be necessary to get fully automated solution. To be honest, I was searching the Helm values for such a flag, just did not find it.

**Comment by howardjohn** [comment]
Hmm, I thought I could reproduce this with `sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1` for testing/local/etc, but that does not seem to trigger the failure

**Comment by aek-dsk** [comment]
@howardjohn : Looks like you are trying to disable the ipv6 network interface only. I think that when using a kernel without ipv6 you don't even have the path "net.ipv6" at all. Please try to disable the kernel module completely e.g. via grub cmd option ipv6.disable=1

**Comment by howardjohn** [comment]
Yeah the bummer is if it needs kernel restart we cannot actually test it in our CI.

**Comment by bleggett** [comment]
We already have an `enableV6` helm flag for `istio-cni` - we can pretty easily share that with ztunnel as well.

**Comment by aek-dsk** [comment]
@bleggett : Sounds good! Probably just the actual behavior of the flag would need some clarification...Enabling is fine, but disabling would need to avoid all ipv6-functionality/calls/dependencies completely.

**Comment by howardjohn** [comment]
https://github.com/istio/ztunnel/pull/1163 should fix this in the next release.

**Comment by edwardzjl** [comment]
Hello, I've encountered an issue with my Istio deployment.

I have an unusual cluster setup where not all nodes have IPv6 disabled. I previously installed istio 1.24.0 in ambient mode using the istio-operator with mostly the default settings.

Recently, I added two nodes with IPv6 disabled, and the ztunnel pods on these nodes keep crashing with the following error:

```console
Error: readiness server starts

Caused by:
    Address family not supported by protocol (os error 97)

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   1: ztunnel::app::build_with_cert::{{closure}}
   2: ztunnel::proxy::{{closure}}
   3: ztunnel::main::{{closure}}
   4: ztunnel::main
   5: std::sys::backtrace::__rust_begin_short_backtrace
   6: main
   7: __libc_start_call_main
   8: __libc_start_main_alias_1
   9: _start
```

I edited the `istio-cni-config` ConfigMap and set `AMBIENT_IPV6: "false"`, then I restarted all the DaemonSets in the `istio-system` namespace,  but the error persists.

How can I disable IPv6 for an already running Istio deployment?

**Comment by edwardzjl** [comment]
I also manually edited the ztunnel DaemonSet to set the following environment variable:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ztunnel
  ...
spec:
  template:
    spec:
      containers:
      - name: istio-proxy
        env:
        - name: IPV6_DISABLED
          value: "true"
      ...
```
However, the error persists.

**Comment by edwardzjl** [comment]
Arrgs, it seems that the environment variable name is `IPV6_ENABLED`, and after setting it to "false" the ztunnel pods stopped crashing. I fogot where I get the `IPV6_DISABLED` from.

As I’m now disabling IPv6 manually, I’m wondering: when I upgrade Istio (likely via `istioctl`), how should I ensure IPv6 remains disabled?

**Comment by edwardzjl** [comment]
> > As I’m now disabling IPv6 manually, I’m wondering: when I upgrade Istio (likely via `istioctl`), how should I ensure IPv6 remains disabled?
> 
> You will have to set the `ambient.ipv6` field of the [istio-cni](https://github.com/istio/istio/blob/f66b1fb747a1ca7587442f39c7bb591198b48dd2/manifests/charts/istio-cni/values.yaml#L55) chart to `false` when upgrading

Thank you for your reply. Yes, I noticed that field in the Helm chart. However, I installed Istio using the Istio Operator, and I’m still new to this tool. I searched the documentation but couldn’t find information on how to configure that field with the Istio Operator.

**Comment by leosarra** [comment]
I think you could merge something like this to your IstioOperator

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    istio_cni:
      ambient:
	    ipv6: false
```
Anyway I believe IstioOperator has been deprecated in 1.23 and removed in 1.24. I recommend switching to Helm.

**Comment by edwardzjl** [comment]
Sorry for my inaccurate expression. I am using `istioctl` not `IstioOperator`.

This is my `config.yaml` when running `istioctl install --revision=1-24-0 --set profile=ambient -f config.yaml`:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    cni:
      enabled: true
    ztunnel:
      enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
  values:
    profile: ambient
```

IDK where to put the `ipv6: false`, tried several places with `istioctl upgrade --dry-run` but all ends up with json unknown field error.

**Comment by leosarra** [comment]
My bad, this is the correct config to use
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    cni:
      enabled: true
    ztunnel:
      enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
  values:
    profile: ambient
    cni:
      ambient:
        ipv6: false
```
