### ISSUE TITLE
Can we create an interface to display the workload information 

### ISSUE THREAD

**Issue by KfreeZ** [istio/ztunnel#114]
Can we retrieve workload infromation inside ztunnel from istioctl ? or via some other approaches?

**Comment by zirain** [comment]
> Can we retrieve workload infromation inside ztunnel from istioctl ? or via some other approaches?

what about `/debug/config_dump?types=wlds` in istiod?

**Comment by hzxuzhonghu** [comment]
A subtask under #114

**Comment by KfreeZ** [comment]
> 

sorry are you referring to #87 ?

**Comment by hzxuzhonghu** [comment]
yes
