### ISSUE TITLE
Investigate DNS proxy port bind issues

### ISSUE THREAD

**Issue by bleggett** [istio/ztunnel#1272]
Reference: https://istio.slack.com/archives/C37A4KAAD/p1724148926299219

**Comment by howardjohn** [comment]
Sorry for the vague comment on slack - I am not sure I agree, I would actually prefer if we bound to localhost for 15001 almost as well.

The only legitimate place to connect to these is from the local pod. if we expose it externally, we can/will have users able to do `curl pod-ip:15053`. This is bad. We have a hack in the 15001 listener to explicitly block these, but would prefer if we don't.

At the very least, we would need to add a similar check for DNS

**Comment by bleggett** [comment]
> The only legitimate place to connect to these is from the local pod. if we expose it externally, we can/will have users able to do curl pod-ip:15053. This is bad. 
> We have a hack in the 15001 listener to explicitly block these, but would prefer if we don't.
Yes, agreed on both. If I avoid localhost, a prerequisite of doing so would be mitigating this without code hacks.

From the perspective of the iptables rules we really don't care what the bound address is.

**Comment by yuval-k** [comment]
this error looks similar https://github.com/kubernetes/ingress-nginx/issues/2904
basically, while ipv6 is enabled, `lo` device doesn't have an ipv6 address assigned to it.

**Comment by bleggett** [comment]
> this error looks similar [kubernetes/ingress-nginx#2904](https://github.com/kubernetes/ingress-nginx/issues/2904) basically, while ipv6 is enabled, `lo` device doesn't have an ipv6 address assigned to it.

Which might explain why restarts fix it but retries do not, as presumably `lo` is created/assigned addresses once, on pod creation.

Seems like options are

- Dynamically do not create a V6 localhost listener in-pod, if the interface doesn't have a V6 address (seems potentially bad/confusing for people -but we could loudly warn).
- Move the DNS listener off of localhost and bind to any/unspecified like the other handlers (which hides the problem).

**Comment by bleggett** [comment]
Closing as this [turned out to be an issue on our end ](https://github.com/istio/ztunnel/pull/1284) (which using UNSPECIFIED addr would have elided, but no need to do so, as long as it isn't needed to work around platform quirks)
