### ISSUE TITLE
Propose changing waypoint_address to be a vec

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/ztunnel#144]
Workload could have multi waypoints instance, workload api could only specify one

**Comment by howardjohn** [comment]
+1,I implemented the control plane side in https://github.com/istio/istio/pull/41903

**Comment by hzxuzhonghu** [comment]
OK, will try to do that

**Comment by hzxuzhonghu** [comment]
I mean in ztunnel

**Comment by howardjohn** [comment]
Implemented now, thanks
