### ISSUE TITLE
Properly report "ready" only when we are ready

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#156]
Ready is defined as:
* XDS is synced
* Listeners are serving
* ?

This is needed for reliability, but also testing.

**Comment by GregHanson** [comment]
is `ready` something that should be displayed via an `istioctl` command, such as `istioctl proxy-status`?

**Comment by howardjohn** [comment]
No, I don't think we need that. We don't for Envoy; its displayed in `kubectl get pods` via the k8s readiness probe

**Comment by howardjohn** [comment]
We could make `proxy-status` show `WDS: SYNCED` or something, but its hard since its a table...

**Comment by howardjohn** [comment]
@keithmattix  is working on this but I cannot assign yet as they aren;'t in the org

**Comment by keithmattix** [comment]
Do we feel like it makes sense to gate readiness on the various listeners being [`run()`](https://github.com/istio/ztunnel/blob/master/src/proxy/mod.rs#L77)? @howardjohn mentioned that XDS is the only outstanding component left, but I think a `BlockReady` makes sense at this point in the code

**Comment by howardjohn** [comment]
we do wait until they are bound so I think that's good enough, the connections can start queueing up at that point

**Comment by PiotrSikora** [comment]
Right now, the readiness is available via `/healthz/ready`, but it's not used by ztunnel itself.

I'd argue that `proxy.run()` should wait _until_ ztunnel is ready (i.e. after local and remote XDS configs are processed), otherwise we're accepting and incorrectly dropping connections.

**Comment by hzxuzhonghu** [comment]
Both make sense, @keithmattix's point is make `run` as another condition to be ready

**Comment by PiotrSikora** [comment]
> Both make sense, @keithmattix's point is make `run` as another condition to be ready

Right, but with current implementation, this means that `proxy.run()` would be executed in parallel with other conditions, leading to a race condition between configuration and proxy listeners (see: #195).

What I'm saying is that we shouldn't start accepting connections until all configuration is processed.

Something like this (ordered):

1. Process configs, fetch XDS, bind to ports, etc.
2. Start accepting connections.
3. Mark server as ready.

**Comment by keithmattix** [comment]
The current block ready implementation is just an unordered hash set of strings signifying a task that must be completed before /admin/ready returns true. If we want to create a dependency graph of actions on startup (e.g process local/remote XDS config before starting listeners before marking ready), we'll likely need some tweaks in the design.

**Comment by howardjohn** [comment]
Could we do:

1. Bind to ports
2. Accept connections
3. Wait for ready
4. Start processing connections

?

Note all of this really only will occur in VM or sidecar use cases; in kubernetes the ztunnel won't get requests while its not ready

**Comment by linsun** [comment]
The startup sequence described earlier https://github.com/istio/ztunnel/issues/156#issuecomment-1330877829 only impacts VMs, and other non k8s env.

Might be good to close this for now and revisit the startup order later on.
