### ISSUE TITLE
Should we consider socket splice for passthrough case

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/ztunnel#158]
Using splice can eliminate copying data from kernel space to user space, and then from user space to kernel space again. 

But splice seems not suitable for telemetry, I am not super sure @howardjohn WDYT?

**Comment by howardjohn** [comment]
Yes SGTM. I think you still get the bytes written so it's not too bad for telemetry.

In Go this happens automagically with io.Copy, not sure what libraries there are to do it in Rust but should be feasible

**Comment by hzxuzhonghu** [comment]
This is fixed by #170 and #179
