### ISSUE TITLE
Define an API for ztunnel to dynamically configure log level

### ISSUE THREAD

**Issue by GregHanson** [istio/ztunnel#165]
similar to `istioctl proxy-config log`, define an API that users can call to dynamically set ztunnel logging level

**Comment by KfreeZ** [comment]
```
curl -X POST /logging To list the loggers
curl -X POST /logging?level={new_level} To change the logging level across all loggers
curl -X POST /logging?level={mod_name}={new_level} To change a particular logger’s level

NOTE: mutilple query parameters is not supported, for example
curl -X POST /logging?"tap=debug&router=debug"
```

**Comment by hzxuzhonghu** [comment]
>curl -X POST /logging To list the loggers

get instead

**Comment by KfreeZ** [comment]
> > curl -X POST /logging To list the loggers
> 
> get instead
I initially make it as a GET, @howardjohn comments we should mirror envoy, it's a POST now, so I am using the POST

**Comment by SkyfireFrancisZ** [comment]
@KfreeZ, is this already done?

**Comment by howardjohn** [comment]
yes
