### ISSUE TITLE
Implement graceful shutdown

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#17]

**Comment by stevenctl** [comment]
Refuse all new connections, wait for existing connections to complete before shutting down.

Kubernetes' default 30 second grace period should probably have a sensible override.

> John’s comment:

1. On SIGTERM, enter "awaiting shutdown". Basically this would just sleep for X seconds.
2. After X seconds, enter "draining"; reject new connections and wait for existing ones. This should last a really long time probably (but outside of scope here to decide how long)
3. Hard shutdown

(1) is important to avoid race conditions where clients are still programmed to send to the ztunnel. once (2) happens, we shouldn't get new connections.

Connection refusals are not retried in ambient world so its important to reduce them

If we can somehow indicate over HBONE that we are draining that is nice too, I haven't thought of any way to do that though.

**Comment by howardjohn** [comment]
#62 implements the basics, but it doesn't do proper shutdown

**Comment by hzxuzhonghu** [comment]
I think still need connection graceful shutdown
