### ISSUE TITLE
Audit tracing usage to ensure we have enough logs, at the right level.

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#18]

**Comment by stevenctl** [comment]
Audit existing logging

Add debug logs at important steps

Log critical errors

Make sure we have appropriate levels to avoid noise

TRACE, DEBUG, INFO, WARN, ERROR

**Comment by EItanya** [comment]
Is part of this adding an admin endpoint to modify the log level?

**Comment by howardjohn** [comment]
No, I think that is different. This is about making sure we are logging useful information, and at a useful level, to make sure the system is debuggable
