### ISSUE TITLE
Setup heap profiling support

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#19]
And make sure existing CPU profiling still works

**Comment by stevenctl** [comment]
Is this working? I see there's a gprof/heap endpoint now

**Comment by howardjohn** [comment]
Basically you can swap out heap allocators, and each one has their own profiling methods. gprof in particular was very hard to compile. I think it could be statically linked but I couldn't figure out how

**Comment by hzxuzhonghu** [comment]
gperftools https://github.com/dignifiedquire/rust-gperftools has not been active for 4 years. Do we still want to use it?

**Comment by howardjohn** [comment]
Aside from 4 years old it also doesn't statically link so I think its probably problematic
