### ISSUE TITLE
Use TLS when proxying `protocol: Tcp` between tunnels.

### ISSUE THREAD

**Issue by PiotrSikora** [istio/ztunnel#194]
My understanding is that we currently have a number of different modes of proxying, depending on the destination:

1) using in-memory zero-copy (when proxying to workloads on the local node),
2) using HBONE over HTTP/2 with TLS (when proxying to workloads on remote nodes with `protocol: Hbone`),
3) using plaintext TCP (when proxying to workloads on remote nodes with `protocol: Tcp`),
4) using plaintext TCP (when proxying to unknown targets, a.k.a. "passthrough mode").

Is there any reason why (3) is done over plaintext TCP and not TLS? I'd assume that we want all traffic between remote nodes to be encrypted.

Also, I definitely miss the background behind the `protocol: Tcp` option. Is it a backup plan in case HBONE overhead is too big, or was it added temporarily for comparison purposes (but we can no longer compare plaintext TCP with plaintext HBONE, since the latter was removed in #186)?

**Comment by howardjohn** [comment]
Case 3 is for when the other workload doesn't have a ztunnel so there is
nothing to terminate the hbone and/or TLS - it's directly to the users
application

**Comment by howardjohn** [comment]
In most clusters I would imagine users have their entire cluster enrolled
in the mesh (and thus use HBONE) but we don't currently require that for
gradual migrations etc

**Comment by PiotrSikora** [comment]
Got it, thanks.
