### ISSUE TITLE
Fetch and cache certificates at workload discovery time

### ISSUE THREAD

**Issue by briansonnenberg** [istio/ztunnel#209]
Split from [this issue](https://github.com/istio/ztunnel/issues/11).  It would be better to fetch and cache during workload discovery instead of during the first request.

- When a new workload on the node is discovered, pre-fetch its cert (if we don't have it yet)
- If we race on explicit fetch_certificate call and pre-fetch, we should only have 1 request to the CA and both await it; a CA request has high cost

**Comment by howardjohn** [comment]
This is done
