### ISSUE TITLE
Support custom extensions

### ISSUE THREAD

**Issue by nmittler** [istio/ztunnel#232]
ztunnel should support custom extensions to allow provider-specific logic to run as part of the processing pipeline. We should at a minimum define a module API. This would allow a provider to build custom ztunnel binaries with their modules wired in.

We should also consider supporting dynamic extension (with WASM, for example). There are a lot of advantages here, such as simplifying upgrades.

**Comment by linsun** [comment]
Not sure if we should allow Wasm? Could you elaborate on how this could simplify upgrade?

**Comment by hzxuzhonghu** [comment]
Not only for L7, but maybe for custom `auth`, protocol extension, etc.
