### ISSUE TITLE
Is this wrong

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/ztunnel#248]
```    
pub async fn find_upstream(&self, addr: SocketAddr, hbone_port: u16) -> Option<Upstream> {
        let _ = self.fetch_workload(&addr.ip()).await;
        let wi = self.info.lock().unwrap();
        wi.find_upstream(addr, hbone_port)
    }
```

The addr is upstream，maybe clusterip. So confused how fetch workload by it?

**Comment by PlatformLC** [comment]
> ```
> pub async fn find_upstream(&self, addr: SocketAddr, hbone_port: u16) -> Option<Upstream> {
>         let _ = self.fetch_workload(&addr.ip()).await;
>         let wi = self.info.lock().unwrap();
>         wi.find_upstream(addr, hbone_port)
>     }
> ```
> 
> The addr is upstream，maybe clusterip. So confused how fetch workload by it?

There is vip -> workloads managed by ztunnel  via xds. So in `find_upstream`, it will first lookup `addr` as clusterip if not, fallthough to lookup as workload_ip.
    fn find_upstream(&self, addr: SocketAddr, hbone_port: u16) -> Option<Upstream> {
        if let Some(wl_vips) = self.vips.get(&addr) {
            // Randomly pick an upstream
            // TODO: do this more efficiently, and not just randomly
            let (workload_ip, target_port) =
                wl_vips.iter().choose(&mut rand::thread_rng()).unwrap();

**Comment by hzxuzhonghu** [comment]
I mean in `        let _ = self.fetch_workload(&addr.ip()).await;` 

```
    pub async fn fetch_workload(&self, addr: &IpAddr) -> Option<Workload> {
        // Wait for it on-demand, *if* needed
        debug!("lookup workload for {addr}");
        match self.find_workload(addr) {
            None => {
                if let Some(demand) = &self.demand {
                    info!("workload not found, sending on-demand request for {addr}");
                    demand.demand(addr.to_string()).await.recv().await;
                    debug!("on demand ready: {addr}");
                    self.find_workload(addr)
                } else {
                    None
                }
            }
            wl @ Some(_) => wl,
        }
    }

    pub fn find_workload(&self, addr: &IpAddr) -> Option<Workload> {
        let wi = self.info.lock().unwrap();
        wi.find_workload(addr).cloned()
    }
```

**Comment by hzxuzhonghu** [comment]
Very confused, it find workload by WorkloadStore.workloads

IIUC the key of  WorkloadStore.workloads is the workload IP not clusterip

**Comment by hzxuzhonghu** [comment]
This is the find_workload implement
```
    fn find_workload(&self, addr: &IpAddr) -> Option<&Workload> {
        self.workloads.get(addr)
    }
```
