### ISSUE TITLE
make tonic build output to src/xxx

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/ztunnel#253]
so that we could use that mod directly and vscode can jump to the definition of the generated code

**Comment by hzxuzhonghu** [comment]
Yes, my vscode could not.  I am using windows and developing via vscode ssh. 


I tried to change to goland ssh, but the goland cost is very huge.

**Comment by howardjohn** [comment]
This is explicitly not recommended: https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script. Tools like https://github.com/dtolnay/cargo-expand can help, also looks like maybe some vscode settings: https://github.com/rust-lang/rust-analyzer/issues/5799

**Comment by hzxuzhonghu** [comment]
https://github.com/rust-lang/rust-analyzer/issues/5799 This does not help

**Comment by daixiang0** [comment]
Maybe we can have a make target for developers who need those files.

**Comment by stevenctl** [comment]
macro expansion is part of rust-analyzer. It's a little less ergonomic to first jump to the macro, then trigger this but it works well enough to skim the generated code as needed. My setup (vim) doesn't give me any proper code navigation within the expanded macro though. Not sure if CLion does. 

I don't think you need any settings, just trigger this action: `rust-analyzer: Expand macro recursively`

source: https://rust-analyzer.github.io/manual.html#expand-macro-recursively

**Comment by hzxuzhonghu** [comment]
After config as https://github.com/hyperium/tonic#getting-started 
```
If you're using [rust-analyzer](https://rust-analyzer.github.io/) we recommend you set "rust-analyzer.cargo.buildScripts.enable": true to correctly load the generated code.
```

it can jump to macro here https://github.com/istio/ztunnel/blob/master/src/xds/types.rs#L31-L36

And then  trigger this action: `rust-analyzer: Expand macro recursively`, it can show the generated file

**Comment by daixiang0** [comment]
> After config as https://github.com/hyperium/tonic#getting-started
> 
> ```
> If you're using [rust-analyzer](https://rust-analyzer.github.io/) we recommend you set "rust-analyzer.cargo.buildScripts.enable": true to correctly load the generated code.
> ```
> 
> it can jump to macro here https://github.com/istio/ztunnel/blob/master/src/xds/types.rs#L31-L36
> 
> And then trigger this action: `rust-analyzer: Expand macro recursively`, it can show the generated file

Does it support autojump? I test at local, it can show but can not jump.

**Comment by hzxuzhonghu** [comment]
No it does not support autojump.
