### ISSUE TITLE
[Question]: is there any plan to support unix domain socket

### ISSUE THREAD

**Issue by KfreeZ** [istio/ztunnel#281]
As we know envoy is supporting UDS.
And ztunnel is working as proxy per node, use the UDS or shared memory mechanism between applications and ztunnel is supposed to be more efficient than TCP/IP socket.

**Comment by hzxuzhonghu** [comment]
This seems not on the high priority task list

**Comment by howardjohn** [comment]
This is not planned or in line with our goals of being a transparent proxy IMO
