### ISSUE TITLE
build failed without using docker

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/ztunnel#307]
cargo build
   Compiling boring-sys v2.1.0
   Compiling thiserror v1.0.37
   Compiling num-integer v0.1.45
   Compiling rayon v1.6.0
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-1.0.37/src/lib.rs:238:34
    |
238 | #![cfg_attr(provide_any, feature(provide_any))]
    |                                  ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `thiserror` due to previous error
warning: build failed, waiting for other jobs to finish...

**Comment by howardjohn** [comment]
This happens when building with nightly compiler then later without in my experience. `cargo clean -p thiserror` resolves.. not sure why its cached
