### ISSUE TITLE
certificates: stop trying to refresh when identity is no longer on the node

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#351]
Currently I think we wil try forever to refresh these identities. Once they are no longer on the node, we don't need them and it will fail when we do try to refresh.

This should probably be done after https://github.com/istio/ztunnel/issues/334  to avoid overlapping work

**Comment by qfel** [comment]
Is this
   1. Stop refreshing on specific error code from the cert service
   2. Add a method to SecretManager to allow explicit prune of specific cert (so that it will stop refreshing)
or both?

I can take a look since I mostly wrapped up #334 (at least the "implement" portion, since no code relies on the warmup functionality yet).

**Comment by howardjohn** [comment]
I think (2). 1 may be transient - we may think we have pod X on our node but the CA doesn't yet (stale cache), so we would want to keep retrying.

The issue I am thinking is

0: istiod says "pod x is on your node". We fetch X identity
1: istiod says "pod x is removed"
2: we continue to refresh X forever

**Comment by keithmattix** [comment]
Has this been implemented?

**Comment by linsun** [comment]
@qfel @howardjohn is this done? I saw https://github.com/istio/ztunnel/pull/421 is merged

can we close this?

**Comment by howardjohn** [comment]
That adds the `forget_certificate` but we don't use it iiuc

**Comment by linsun** [comment]
@adiprerepa  are you working on this, or should we unassign?

**Comment by linsun** [comment]
cc @ilrudie while i think this is nice to have for beta, probably not a blocker.

**Comment by ilrudie** [comment]
Looks like it's been assigned. @adiprerepa, are you actively working on this?

**Comment by adiprerepa** [comment]
@ilrudie I was, no longer though. feel free to unassign.

**Comment by ilrudie** [comment]
I've opened #818 with an initial implementation of forgetting certs

**Comment by ilrudie** [comment]
Yeah, Its still an problem afaik. I didn't love the impl in 818 and John had also expressed some concerns. I decided it needed a full rework so closed the old issue
