### ISSUE TITLE
Verify inbound certificates properly

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#359]
Currently, we only check the full SAN with a authz policy. otherwise we only check the root cert.

We also need to check the trust domain matches to get parity with Envoy's enforcement.

We should also double check (ie actually test) the root cert check actually happens, just in case - but it does appear to be there.

**Comment by keithmattix** [comment]
I'll take this one. Should the server just validate that the SAN is part of the same trust domain?

**Comment by howardjohn** [comment]
Yeah that is the default check; Authz can do a more precise check if user explicitly configures it. So I think we need that default check ("default" is maybe misleading, we should do it all the time and authz is on top)
