### ISSUE TITLE
remote dev containter lint fix

### ISSUE THREAD

**Issue by ilrudie** [istio/ztunnel#360]
Consider use of:
```Dockerfile
RUN ["/bin/bash", "-c", "set -o pipefail && useradd ..."]
```
instead of:
```Dockerfile
# ignoring because the current shell doesn't support pipefail; likely want to have a better fix long term
# hadolint ignore=DL4006
RUN useradd -lm \
  -u $REMOTE_USER_ID \
  -G $REMOTE_USER_GROUPS \
  -d $REMOTE_USER_HOME \
  -s $REMOTE_USER_SHELL \
  $REMOTE_USER \
  && yes $REMOTE_USER_PASSWORD | passwd $REMOTE_USER
```
to address linter concerns in `docker/remote-env/Dockerfile`.

I don't believe that exact syntax is understood by the linter but it could be along the right lines.

Please remove `hadolint` ignore directive if fix is adopted which addresses the linter warning. Potentially can adopt the use of bash for this line to allow pipefail but keep the linter directive to avoid the warning.

**Comment by zirain** [comment]
fixed by https://github.com/istio/ztunnel/pull/355
