### ISSUE TITLE
TCP Bytes metrics: report on interval

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#368]
Currently, we report these counts only on connection close. We should report them periodically as well, so we get visibility into long running requests

**Comment by hzxuzhonghu** [comment]
Not sure how it can be done, because we use mang libs. tokio copy and even splice

**Comment by howardjohn** [comment]
Yes I have some concerns about it too. Might not be feasible.

Btw I did send a PR to the splice library so we can at least get metrics once connection closes

**Comment by linsun** [comment]
cc @ymesika @yuval-k who discussed similar issue in the past

**Comment by ymesika** [comment]
I guess it can be achieved by having a wrapper struct around the streams (TCP / halves) that does the bytes counting with minimal footprint.
Similar to @yuval-k 's wrappers in the extension PR.

@howardjohn the PR you refer to is only for the zero-copy path, isn't it? the other relay methods are covered.

**Comment by howardjohn** [comment]
We have realm copy and tokio copy, both are very similar code, and we get the metrics once it is complete.

**Comment by howardjohn** [comment]
This is implemented
