### ISSUE TITLE
ProxyConfig reading from file is not auto-updated

### ISSUE THREAD

**Issue by hanxiaop** [istio/ztunnel#425]
Currently, we only read the configuration file once from `/etc/istio/config/mesh`. We should watch for changes to the file and update the current configuration if there are any new changes.

**Comment by howardjohn** [comment]
Its not clear to me how feasible most, if not all, of these are to live-reload. We don't for envoy

**Comment by hzxuzhonghu** [comment]
Reading from it once is ok in most cases, do not introduce much complexity before any use is necessary. Most parameters here cannot be changed after process starting up
