### ISSUE TITLE
Ztunnel log format is not matching the Istio standard

### ISSUE THREAD

**Issue by hanxiaop** [istio/ztunnel#453]
The log format with colors is not readable directly when fetched via the bug-report.
https://github.com/istio/istio/pull/43878#discussion_r1132611318

**Comment by MorrisLaw** [comment]
Hey @hanxiaop , I noticed this issue and was going to look into it. But it seems that you've already made the PR to fix it?

Should we close this out now? Or is there more work to be done?

**Comment by hanxiaop** [comment]
> Hey @hanxiaop , I noticed this issue and was going to look into it. But it seems that you've already made the PR to fix it?
> 
> Should we close this out now? Or is there more work to be done?

@MorrisLaw I've only added the Ztunnel log to the bug report. However, if you look at the log format of other components and Ztunnel, you'll see a few differences. I was trying to address this earlier, but it appeared that it may require a lot of work. FYI, this https://github.com/istio/ztunnel/pull/476#discussion_r1147182614 might contain more details. If you're interested, feel free to unassign me and take on the work.
