### ISSUE TITLE
NPE with multicluster

### ISSUE THREAD

**Issue by costinm** [istio/ztunnel#481]
Recording a bug on 2835a206aca4e3d00d49e9a71a2c3423f8c2e7f0 (Mar 18) - after adding the multicluster secrets.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x2b331d1]

goroutine 4488 [running]:
istio.io/istio/pilot/pkg/serviceregistry/kube/controller.(*Controller).Policies(0xc002f1a2c0, 0x0)
	istio.io/istio/pilot/pkg/serviceregistry/kube/controller/ambientindex.go:222 +0x71
istio.io/istio/pilot/pkg/serviceregistry/aggregate.(*Controller).Policies(0x3d080e8?, 0xc000082030?)
	istio.io/istio/pilot/pkg/serviceregistry/aggregate/controller.go:98 +0xfb
istio.io/istio/pilot/pkg/xds.WorkloadRBACGenerator.GenerateDeltas({0x40babd?}, 0x323e320?, 0x31bfe40?, 0xc000af8bd0)
	istio.io/istio/pilot/pkg/xds/workload.go:145 +0x1c3
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).pushDeltaXds(0xc000eb6a00, 0xc0003faf00, 0xc000af8bd0, 0xc0025b6780)
	istio.io/istio/pilot/pkg/xds/delta.go:466 +0x37b
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).processDeltaRequest(0xc000eb6a00, 0xc0037906c0, 0xc0003faf00)
...

I have an authz in one cluster only. but I suspect something is wrong with the MC init, will get master and see if it still happens.

**Comment by hzxuzhonghu** [comment]
This is always the same. I can see we only set configController for the config cluster. Need a fix
