### ISSUE TITLE
Ambientindex appears to only watch pods ?

### ISSUE THREAD

**Issue by costinm** [istio/ztunnel#485]
I was working on cluster.local, and if I read the ambientindex.go code correctly it only returns the pod IPs.

We also have WorkloadEntry and probably ServiceEntries created by controllers or user that are not local pods. 

Also getPodsInService returns nil if the Service has no selector - it should return the EndpointSlices. 
If it has selector - it must add the WorkloadEntries.

**Comment by costinm** [comment]
Also watch any endpoints loaded from federated XDS sources, etc - basically the same thing that EDS returns.

**Comment by howardjohn** [comment]
Not implemented yet.

Endpoints from XDS is generally a broader problem, IMO. The ambient code
would just read "Endpoints", wouldn't care where they are from if we have
the proper abstraction. But today we only read istio CRDs over XDS.

Part of it will also read ServiceEntry and WE so if you can send that over
XDS it should just work

**Comment by stevenctl** [comment]
https://github.com/stevenctl/istio/tree/ambient/vm
https://github.com/istio/istio/pull/43799

Some basic support here if you just need it to experiment. WorkloadEntry focused.

**Comment by costinm** [comment]
I was just reading the code ( working on cluster.local ) - no need to rush it, but we should have it before we ship 1.18 I think. 

I am also worried about EndpointSlice - the slices are attached to a Service, but don't have labels so the current method (apply the selector on Pods and in your PR WorkloadEntry) won't work. 

I think merging the ServiceInstances is best - and better than dealing with WorkloadEntry in the 'services' lookup. 
We still need WorkloadEntry for the pod-to-pod - and we may have a gap in telemetry for endpoints that are only
present in EndpointSlice ( but not on security - EndpointSlice has serviceAccount AFAIK)

**Comment by howardjohn** [comment]
endpointslice only really has node name, IP, and port unfortunately. Not
much useful - but enough to at least route to it. There is also an ownerRef
to a Pod for the normal ones but I think we are talking about custom slices
here.

**Comment by costinm** [comment]
Yes, you are right - there is no ServiceAccount. But that's fine - we have
the namespace and we may require a ServiceEntry
to associate a specific service account.

We won't have the 'hbone available' either - but I think it's reasonable to
say 'for EndpointSlices without an associated Pod
or WorkloadEntry or labels - we default to hbone'.

I think ServiceImport now has service account.

**Comment by howardjohn** [comment]
Everything is watched now
