### ISSUE TITLE
DNS in Ambient Mesh

### ISSUE THREAD

**Issue by nmittler** [istio/ztunnel#487]
This is a top-level issue to track DNS as a feature for ambient mesh. In Istio, the control plane programmed pilot-agent, which acted as a DNS proxy for the container. Since ztunnel is not using pilot-agent and can also be multi-tenant, we need a path forward for DNS.

The first part of this work is to propose a design for ambient DNS. Should consider both single and multi-tenant scenarios. It should also discuss possible choices for technology (e.g. should we use an existing DNS solution? Should we build one from scratch?).

**Comment by nmittler** [comment]
RFC is [here](https://docs.google.com/document/d/1EZDMZXgy4N-OjPC-FUvUdKwXewibxeowEWm1B20UeqE/edit#)

**Comment by nmittler** [comment]
Re-opening until we have DNS added to our E2E testing of ztunnel.

**Comment by howardjohn** [comment]
DNS is implemented and tested now, closing this out. thanks everyone
