### ISSUE TITLE
`TERMINATION_GRACE_PERIOD` ztunnel setting

### ISSUE THREAD

**Issue by bleggett** [istio/ztunnel#519]
xref: https://github.com/istio/istio/pull/44813#issuecomment-1547953730

Inside of K8S, ztunnel's TERMINATION_GRACE_PERIOD setting overlaps with/conflicts with the K8S `terminationGracePeriodSeconds` property. 
  - ztunnel's `TERMINATION_GRACE_PERIOD` configures how long ztunnel blocks after getting a SIGTERM to finish draining its connections, before giving up and exiting.
  - K8S's `terminationGracePeriodSeconds` is a standard K8S pod prop that configures how long K8S waits after sending a SIGTERM to ztunnel before it gives up waiting and sends e.g. a SIGKILL.

Problem:
  - Objections were raised to auto-configuring ztunnel's `TERMINATION_GRACE_PERIOD` to be a value smaller than the K8S-configured `terminationGracePeriodSeconds` property in our Helm chart.
  - Objections were raised to exposing both properties individually in our Helm chart
  - If the K8S setting exists, the ztunnel setting _must_ be smaller than the K8S setting to avoid unexpected behavior.
  - Simply removing `TERMINATION_GRACE_PERIOD` as a config option entirely from ztunnel works in a K8S context, but creates problems when running ztunnel outside of K8S (VMs, etc) - without an internal grace period setting, ztunnel needs an external reaper/watchdog to handle that.
 
 
Suggestion:
  - If we really don't want to autoset the ztunnel property based on the K8S property value in our helm chart, and we can't remove one of the options, then suggest we overload `TERMINATION_GRACE_PERIOD` to accept e.g. `-1`, which tells ztunnel to block indefinitely draining connections, until/unless an external watchdog (K8S, systemd, whatever) terminates it.

**Comment by bleggett** [comment]
> I don't really love the idea of having ztunnel block indefinitely. 

~block indefinitely~ block until it receives a stronger TERM signal, or it successfully drains all its connections.

> If k8s (or another external watchdog) just ends the process I think the likelihood of having connections which are no longer valid but were never closed is going to go up.

We can't control what the process scheduler does, but almost all of them support "ask, wait, then ask less nicely". ztunnel has no real control over how long that wait is, regardless. Could be zero seconds, could be a week. Current connection termination behavior is we do what we can before our scheduler reaps us.

**Comment by bleggett** [comment]
> If you have `-1` would ztunnel just close connections at it's own maximum possible aggression and block only until the connections are terminate or it get's a stronger signal? 

Yes, that's the proposal.

**Comment by howardjohn** [comment]
But when it gets SIGKILL it cannot gracefully cleanup, its force closed,
right? I think that is  Ian's concern

**Comment by bleggett** [comment]
> But when it gets SIGKILL it cannot gracefully cleanup, its force closed, right? I think that is Ian's concern

Yep - if it hasn't finished by the time SIGKILL (or whatever) comes around, it will be forcibly terminated.

That's a problem with or without TERMINATION_GRACE_PERIOD tho, we have no actual control over when whatever process scheduler running ztunnel decides to give up waiting for ztunnel to exit cleanly.

**Comment by howardjohn** [comment]
yeah but if ztunnel decides to exit it can shutdown the connections vs the
process just exiting? TBH I don't know for sure what differences this ends
up being in practice

**Comment by howardjohn** [comment]
1. SIGTERM: start draining
2. past TERMINATION_GRACE_PERIOD: ztunnel decides to exit
3. SIGKILL: process killed abruptly.

-1 means we lose (2) and go straight to (3)?

**Comment by bleggett** [comment]
> 1. SIGTERM: start draining
> 2. past TERMINATION_GRACE_PERIOD: ztunnel decides to exit
> 3. SIGKILL: process killed abruptly.

> -1 means we lose (2) and go straight to (3)?

-1 means 

1. SIGTERM: start draining
2. Exit when fully drained, or get SIGKILL, whichever comes first.

**Comment by howardjohn** [comment]
I don't think you can catch sigkill though. you just die

**Comment by ilrudie** [comment]
> 1. SIGTERM: start draining
> 2. past TERMINATION_GRACE_PERIOD: ztunnel decides to exit
> 3. SIGKILL: process killed abruptly.
This is what I thought the "ideal" shutdown should look like. If we have `TERMINATION_GRACE_PERIOD` set to -1 would we essentially skip over the "start draining" phase and move directly into the we're exiting now so here are at least some RST?

**Comment by bleggett** [comment]
> > 1. SIGTERM: start draining
> > 2. past TERMINATION_GRACE_PERIOD: ztunnel decides to exit
> > 3. SIGKILL: process killed abruptly.
> 
> This is what I thought the "ideal" shutdown should look like. If we have `TERMINATION_GRACE_PERIOD` set to -1 should we essentially skip over the "start draining" phase and move directly into the we're exiting now so here are at least some RST?

> Ideally ztunnel would always FIN & RST all it's connections. 

We can't FIN if ztunnel has no idea how long the process scheduler will wait before SIGKILL, correct.

We have to start RST on SIGTERM. Or, we go back to the initial proposal I made and set `TERMINATION_GRACE_PERIOD` to a strictly smaller value than the process scheduler's grace period, giving us a guarantee that we won't get a SIGTERM until we best-effort FIN everything.

**Comment by ilrudie** [comment]
My main overarching concern is that we're moving from a paradigm of sidecars where essentially a connection to your local istio proxy cannot fail and your client is free to be as poorly behaved as it wants. That's not 100% accurate but it's trying to approach that limit so to speak. With ztunnel we are introducing a client case of "my local istio proxy actually went away and I need to do something about it" so IMO ztunnel should be as well behaved as we can possibly make it. Give things a fighting chance.

I know from personal experience there are network libs that are happy to ignore FIN and RST from a server and expect to be in full control of connection lifecycle at all times. Not much we can do about that really. I guess use a sidecar. For the rest though not ghosting a connection will probably be the better option even if connections are ending more abruptly than we would ideally hope for.

**Comment by howardjohn** [comment]
We can't RST on SIGTERM or it breaks the TERMINATION_GRACE_PERIOD. The goal
of TERMINATION_GRACE_PERIOD is not to terminate all connections, it's to
let them drain naturally. if we terminate them it impacts the user. Ideally
user doesn't have too long lived connections, and naturally we get to zero
connections.

in practice, not all connections will meet this criteria, so we have to cut
it off at some point. But not immediately..

> Or, we go back to the initial proposal I made and set
TERMINATION_GRACE_PERIOD to a strictly smaller value than the process
scheduler's grace period, giving us a guarantee that we won't get a SIGTERM
until we best-effort FIN everything.

SIGTERM is always the first thing thathappens

**Comment by howardjohn** [comment]
I think the correct fix is to use TERMINATION_GRACE_PERIOD as the primary mechanism, and just make the pod setting +1min or something, just as a backstop incase ztunnel is broken and doesn't exit when it should. I agree that makes the helm discussion back in picture, but @ilrudie 's point that we would not gracefully shutdown with SIGKILL is more problamtic IMO.

**Comment by bleggett** [comment]
@costinm thoughts/suggestions on above?

**Comment by bleggett** [comment]
> Yet another NIH way to stop processes ?

No, just that `ztunnel`, like all proxies, needs to be informed of what time window it has to gracefully FIN connections.

The time window `ztunnel` has to gracefully FIN connections is the time window between SIGTERM and SIGKILL.

Once `ztunnel` gets SIGKILL, it's out of time and cannot do anything in response to that but be killed immediately.

So, if the platform (k8s, systemd) has a grace period after SIGTERM before it sends SIGKILL, `ztunnel` needs to know that it has LESS-THAN that amount of time to wait for clients to gracefully accept FIN-style connection closes, before forcefully sending RST connection closes.

**Comment by costinm** [comment]
On Tue, May 16, 2023 at 9:31 AM Ben Leggett ***@***.***>
wrote:

> Yet another NIH way to stop processes ?
>
> No, just that ztunnel, like all proxies, needs to be informed of what
> time window it has to gracefully FIN connections.
>

Ztunnel can't FIN the streams forwarded to the app - app can gracefully
FIN.

Ztunnel can send GO-AWAY or stop accepting - and for that we have SIGTERM.

Envoy and ztunnel as a sidecar are a different story from ztunnel as
per-node server.


> The time window ztunnel has to gracefully FIN connections is the time
> window between SIGTERM and SIGKILL.
>
Once ztunnel gets SIGKILL, it's out of time and cannot do anything in
> response to that but be killed immediately.
>
> So, if the platform (k8s, systemd) has a grace period after SIGTERM before
> it sends SIGKILL, ztunnel needs to know that it has LESS-THAN that amount
> of time to wait for clients to gracefully accept FIN-style connection
> closes, before forcefully sending RST connection closes.
>

I still don't understand what ztunnel would do after between the end of the
drain duration set and SIGKILL.
After SIGTERM - stop accept, send GO-AWAY.
After DRAIN_DURATION - ????
SIGKILL automatically sends RST on all remaining connections.

**Comment by howardjohn** [comment]
The claim about was SIGKILL would not result in RSTs. If actually does, I
agree. If it does not thenI think we need that?

**Comment by ilrudie** [comment]
I don't think ztunnel can react to a SIGKILL to send RST. Anything it want's to send must be sent prior in response to the SIGTERM.

**Comment by bleggett** [comment]
> Ztunnel can't FIN the streams forwarded to the app - app can gracefully FIN. Ztunnel can send GO-AWAY or stop accepting - and for that we have SIGTERM. Envoy and ztunnel as a sidecar are a different story from ztunnel as per-node server.

Do we need ztunnel to FIN outbound connections it's proxying to upstream servers? If not, and it can just forcibly close them all, then we don't need it.

ztunnel needs to send GOAWAY to clients, and close the connection, and it can start doing this on SIGTERM, yes.

**Comment by ilrudie** [comment]
Real basic unscientific local test. If I let this run its course I see the drop printed. If I `kill -9` the pid it never drops.

```rust
use std::{thread, time};

struct Droppable {
    name: &'static str,
}

impl Drop for Droppable {
    fn drop(&mut self) {
        println!("> Dropping {}", self.name);
    }
}

fn main() {
    let _a = Droppable { name: "testing" };

    let delay = time::Duration::from_secs(30);

    thread::sleep(delay);
}
```

**Comment by bleggett** [comment]
> Real basic unscientific local test. If I let this run its course I see the drop printed. If I `kill -9` the pid it never drops.
> 
> ```rust
> use std::{thread, time};
> 
> struct Droppable {
>     name: &'static str,
> }
> 
> impl Drop for Droppable {
>     fn drop(&mut self) {
>         println!("> Dropping {}", self.name);
>     }
> }
> 
> fn main() {
>     let _a = Droppable { name: "testing" };
> 
>     let delay = time::Duration::from_secs(30);
> 
>     thread::sleep(delay);
> }
> ```

It doesn't matter tho - there's no implicit `wait` in that scenario. When you get SIGTERM you start dropping connections. Whether they're all dropped by the time you get the followup SIGKILL is moot, you have no control over that anyway and that could take an indeterminate amount of time (something between 0 and very small).

**Comment by ilrudie** [comment]
The test was just whether the drop mechanism in RUST would somehow allow it to send a RST after getting SIGKILL which seems to be no.

**Comment by howardjohn** [comment]
We don't drop connections on SIGTERM, otherwise its not a graceful shutdown. if we did then its trivial. The SIGTERM signals "stop _accepting_ new connections, and wait for the clients to politely close connections". There is no point closing the client connections early unless we are about to shutdown immediately after.

**Comment by bleggett** [comment]
> We don't drop connections on SIGTERM, otherwise its not a graceful shutdown. if we did then its trivial. The SIGTERM signals "stop _accepting_ new connections, and wait for the clients to politely close connections". There is no point closing the client connections early unless we are about to shutdown immediately after.

That depends so much on specific client config, is it very useful for a ztunnel to stop accepting connections? We could just as easily stop redirecting connections to ztunnel in e.g. CNI, in which case a refusal window in zt proper doesn't matter.

Even without that tho I'm not sure it's very useful.

If ztunnel's `TERMINATION_GRACE_PERIOD` == 30 secs (and the platforms is, say, 1 sec greater, 31 sec)

- "Client, I will stop accepting new connections now. If you happen to close your connection in that window good, if not, then the grace period means nothing to you"
- (after say 20 seconds of not accepting new connections, ztunnel allocates the remaining 10 secs for GOAWAY/RST)

**Comment by howardjohn** [comment]
Yes, long lived connections are broken. That is why we should avoid killing ztunnel as much as possible (for example, time it with a node upgrade), and use very long grace periods when we do have to (far longer than 30s - more like 30h)

**Comment by howardjohn** [comment]
In waypoint/sidecar this is better btw, since we can send GOAWAY and `connection: close`. But cannot signal to apps for raw TCP

**Comment by bleggett** [comment]
Do we care about ztunnel needing to gracefully (i.e. with a window) terminate its _upstream_ connections?

That's the only scenario where I think `TERMINATION_GRACE_PERIOD` is really needed as a ztunnel setting, to @costinm 's point

**Comment by costinm** [comment]
I am 100% sure killing a process sends RST.

Upstream tcp connections can't be gracefully closed either - we don't
control the ends, would be a bug if ztunnel sent a FIN when the local pod
didn't initiate it and may have in flight data.

I do agree ztunnel stop should be very long - but that may be independent.
You can cordon a node for 24 h - and if we implement the swapping, whatever
controls the process can coordinate it independent of k8s process( which is
not designed for node-wide critical services).

**Comment by costinm** [comment]
Sorry - kernel sends FIN actually when the process dies, RST in some cases.

**Comment by bleggett** [comment]
> Sorry - kernel sends FIN actually when the process dies, RST in some cases.
> 

FIN when client, RST when server, on socket events, regardless of whether the process is still technically there or not - ok, that makes sense.

> Upstream tcp connections can't be gracefully closed either - we don't control the ends, would be a bug if ztunnel sent a FIN when the local pod didn't initiate it and may have in flight data.

Yep, I was thinking more we might need to signal the server in a timely fashion that the connection has ended.

But it sounds like a courtesy FIN will be sent, for that purpose.




Ok, then to summarize - I don't see a good argument for a discrete ztunnel config setting for termination grace.

How long it stays up is not up to ztunnel to manage, and whether new connections are redirected to it isn't up to ztunnel to manage either.

**Comment by bleggett** [comment]
> Sorry - kernel sends FIN actually when the process dies, RST in some cases.
> 

FIN when client, RST when server, on socket events, regardless of whether the process is still technically there or not - ok, that makes sense.

> Upstream tcp connections can't be gracefully closed either - we don't control the ends, would be a bug if ztunnel sent a FIN when the local pod didn't initiate it and may have in flight data.

Yep, I was thinking more we might need to signal the server in a timely fashion that the connection has ended.

But it sounds like a courtesy FIN will be sent either way, for that purpose.




Ok, then to summarize - I don't see a good argument for a discrete ztunnel config setting for termination grace.

How long it stays up is not up to ztunnel to manage, and whether new connections are redirected to it isn't up to ztunnel to manage either - in fact to extend @ilrudie's point above, ztunnel itself actively refusing connections still being routed to it would likely cause issues with clients not expecting that.

**Comment by costinm** [comment]
Termination is a very tricky subject. Sorry for the misinformation and
confusion between RST and FIN, it's been ~10 years since I debugged FIN/RST
in depth.
There is much more - some kernels throttle and drop FIN/RST after a certain
rate, TLS has it's own termination handshake - and usually
applications making TCP connections don't have good ways to differentiate
or detect if the connection is still alive. And a machine crash or network
problems may also result in lost FIN/RST.

Even in normal operation (not shutdown) - I don't know if ztunnel can
detect if either side sends a RST instead of FIN and propagate it.

But I think the main issue here is that while the upgrade for Ztunnel
requires a (very) long drain, this env variable doesn't seem  the
right place. CNI + code that will drive the shift/upgrade  - or whatever
drives the node cordon process will have the power to coordinate this.

One thing to research is if when a node is upgraded, after cordon, the pods
are terminated in any order and what is the timeout
on the node shutdown, i.e. what happens if a pod takes 1 week to terminate
? If ztunnel is the last standing - we should be safe.

**Comment by howardjohn** [comment]
> ztunnel itself actively refusing connections still being routed to it would likely cause issues with clients not expecting that, versus just proactively redirecting new connections and externally starving ztunnel of new ones.

Not sure I agree with this necessarily. Its better to reject a new connection then to accept a connection and drop it later.

However, we also cannot start rejecting immediately since there is some propogation delay before clients stop sending us new connections. Probably fine to just accept them, but I don't think its _ideal_

**Comment by bleggett** [comment]
> Not sure I agree with this necessarily. Its better to reject a new connection then to accept a connection and drop it later.

Agree, but I'm saying that ideally (and probably necessarily)`cni` is in charge of whether a ztunnel pod sees a new connection to begin with, and can simply choose to not send any new connections to a (cordoned, or obsoleted, or whatever) ztunnel pod, starving it naturally. ztunnel doesn't need to reject _new_ connections because it would never see them, once `cni` decided to begin starving it.

**Comment by ilrudie** [comment]
Maybe I just missed it but I don't think the proposal has been summarized in one post. As I understand it what's being put forth is something like:

1. Decision to terminate a ztunnel is made and externally implemented. Ztunnel is not aware of this and continues to operate normally.
2. "Grace period" for connection draining occurs.
3. ztunnel receives SIGTERM. Upon handling the signal it immediately begins closing any existing connections (which would ideally be few/zero after the drain).
4. ztunnel has no more work to do and terminates gracefully or get's SIGKILLed.
5. (if necessary) Kernel closes any remaining connections ztunnel wasn't able to close itself.

**Comment by costinm** [comment]
John: there are 2 upgrade models mixed in this thread. For 'cordon' model,
ztunnel continues accepting connections and working normally. The node will
not schedule new pods and existing pods will be stopped. This is commonly
used to upgrade the kernel or kubelet on nodes.

The second mode is a hot swap driven by CNI - new ztunnel on same node. I
don't know how we want to do this - if it is a brand new pod, we also need
to keep listening and process everything until the new pod is ready and
propagated, followed by a goaway so new streams go to new pod. If it is
using a new ztunnel binary in the same pod - without CNI intervention - the
second ztunnel could listen on same port and old one stop accepting. I
guess this is different enough to be treated as 3rd mode.




On Wed, May 17, 2023, 08:19 Ian Rudie ***@***.***> wrote:

> Maybe I just missed it but I don't think the proposal has been summarized
> in one post. As I understand it what's being put forth is something like:
>
>    1. Decision to terminate a ztunnel is made and externally implemented.
>    Ztunnel is not aware of this and continues to operate normally
>
>
>    1. "Grace period" for connection draining occurs.
>
>
>    1. ztunnel receives SIGTERM. Upon handling the signal it immediately
>    begins closing any existing connections (which would ideally be few/zero
>    after the drain).
>
> Send goaway. Maybe stop accepting new connections ( mode 3).  But not
close existing connections.

If the connections naturally close and no new ones get created - which
would happen since xds advertises the new pod (in mode 2) or pods are
terminated (mode 1) - if connection count is zero it may exit. Maybe... We
need to put each mode in a doc and consider all cases...

>
>    1. ztunnel has no more work to do and terminates gracefully or get's
>    SIGKILLed.
>
>
That's the question - how to determine no more work is true. Mode 1 - no
more pods on the node. Mode 2 - zero connections, but what if XDS update
didn't propagate and some client keeps sending to old pod ? Can we just let
it alive and not used until next upgrade ( blue/green).


>    1. (if necessary) Kernel closes any remaining connections ztunnel
>    wasn't able to close itself.
>
> I don't think ztunnel should ever close streams. Idle h2 connections -
yes, goaway - in mode 2 and 3 ( not 1)

When kubelet runs out of patience - it'll be killed by kernel and nothing
we can do, close will be called.

**Comment by howardjohn** [comment]
Cordon still tries to terminate ztunnel, no? And thus gets a SIGTERM?

In all cases the signal to start "draining" is a SIGTERM in my mind?

Where "Drain" means "exit when we have no work left (zero connections)"

> GOAWAY

I don't think this is useful since we are an L4 proxy. Closing the h2 connection vs GOAWAY is effectively the same -- the client ztunnel will close the app connection. We have no mechanism to signal to the application it should close the connection.

**Comment by ilrudie** [comment]
+1 for document the models more clearly so we can understand what exactly we're agreeing on.

I like @howardjohn's way to begin with SIGTERM to the ztunnel I think. At least in a k8s context it seems like a good signal to be able to handle as gracefully as possible. It wouldn't preclude some other way of initiating a drain event necessarily but would likely provide a better outcome in the event that a cluster administrator didn't follow istio-specific drain steps.

**Comment by bleggett** [comment]
> In all cases the signal to start "draining" is a SIGTERM in my mind?

That's fair if we want that model - even in that case, we still don't need `TERMINATION_GRACE_PERIOD`, so for now it makes sense to proceed with removing that.

**Comment by ilrudie** [comment]
`kubectl cordon <node>` prevent scheduling of most new pods
`kubectl drain <node>` evict everything that's not managed by a daemonset, while respecting PDBs
`kubectl drain --ignore-daemonsets <node>` evict everything including pods managed by a daemonset

Drain also cordons the node.

**Comment by bleggett** [comment]
> The second mode is a hot swap driven by CNI - new ztunnel on same node. I don't know how we want to do this - if it is a brand new pod, we also need to keep listening and process everything until the new pod is ready and propagated, followed by a goaway so new streams go to new pod.

CNI hotswap is not terribly hard to do with e.g. eBPF, as long as we can keep 2 ztunnel pods SxS on the same node for some amount of time.

But - how we do this is technically OOS for this issue.

**Comment by costinm** [comment]
I think cordon/drain may send sigterm.

But we may need a flag to indicate the upgrade mode - for cordon we would
not do anything, just wait.

**Comment by ilrudie** [comment]
Cordon prevents new pods from being scheduled onto a node (in most cases, there are some workloads which are allowed to schedule onto cordoned nodes IIRC). Cordon shouldn't terminate any running pods on the node though.

I've used cordon in the past to prevent envoy from being scheduled onto a node I suspected was unhealthy. Everything on the node kept running and I had to delete my failing envoy pod to get it rescheduled onto a healthy node.

**Comment by costinm** [comment]
You are right - I'm using 'cordon' as a shortcut for the process normally
used to upgrade kubelet/kernel on a node.

Ztunnel and CNI are simpler and should be more stable than full
envoy/sidecars/Istio - and if we do it right the 'contracts' can
be stronger and simpler, so upgrade of Istiod and waypoints is decoupled.
In this case - having ztunnel/cni upgraded
at the same rate as K8S releases and node updates is least disruptive and
safest option ( also simplest for us, least work)

**Comment by ilrudie** [comment]
It would definitely be easier to manage connections during termination if we can more or less count on the node being drained before ztunnel gets sigterm.

**Comment by costinm** [comment]
My main goal is for ztunnel docs to provide 'ztunnel and cni upgrade using
the same process and ideally at the same time with node' as a recommended
upgrade path.

I am all for smarter options in Istio-CNI - like eBPF or moving connections
or having A/B - but I also believe the 'capture traffic for a pod'
should become a feature of the underlying CNI, not specific or tied to
Istio ( all other mesh implementations use something similar ), because
our hacking of underlying CNI is dangerous and prevents users from changing
the mesh or using multiple meshes. And I don't think it is
a huge effort for a CNI provider to do this redirection, Cilium already has
a subset of this (single port) with a CRD.

If native CNI starts providing interception controls - users of those CNI
vendors wouldn't need istio-cni installed, they can use
multiple mesh implementations in the same cluster if they want - but the
upgrade of ztunnel using fancy tricks in istio-cni will no
longer be available. And by the time this happens - ztunnel will hopefully
be stable and tested enough that it doesn't need
frequent upgrades.

**Comment by costinm** [comment]
On Thu, May 18, 2023 at 7:22 AM Ben Leggett ***@***.***>
wrote:

> Cilium already has a subset of this (single port) with a CRD. If native
> CNI starts providing interception controls - users of those CNI vendors
> wouldn't need istio-cni installed, they can use multiple mesh
> implementations in the same cluster if they want - but the upgrade of
> ztunnel using fancy tricks in istio-cni will no longer be available. And by
> the time this happens - ztunnel will hopefully be stable and tested enough
> that it doesn't need frequent upgrades.
>
> Very OTT to this issue but:
>
> Totally agree - but that doesn't preclude istio-cni-esque node agent that
> configures redirection using native CNI, and which can/will manage ztunnel
> starve/termination via redirect config.
>

If native CNI provides redirection - installer would create whatever CRDs
are needed, but we won't need to run istio-cni ( with the high permissions
),
just ztunnel. Other meshes would do the same. The main value of 'native'
redirection is that mesh vendors don't have to each install their own
vendor-cni or require very high permissions. If we need a controller to
create the CNI-redirect CRDs - I suspect that would be Istiod, not a daemon
set.

**Comment by bleggett** [comment]
Merged in https://github.com/istio/ztunnel/pull/522, closing this.
