### ISSUE TITLE
hyper client "not implemented" on tonic error

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#525]
```
thread 'main' panicked at 'not yet implemented', /usr/local/google/home/howardjohn/.cargo/git/checkouts/hyper-util-7fd38a0cfc1cd33b/b9eaeca/src/client/legacy.rs:743:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I thought it could only happen in tests but looks like in real world its happening as well. need to imlpement it in hyper client or stop using it

**Comment by film42** [comment]
I opened a PR to hyper-util with error conversions (removing `todo()`s), but I'm not sure if it's way off or not. If it looks right, feel free to merge it into your branch since Cargo.toml is pointed at your fork atm.

**Comment by ilrudie** [comment]
Quick status update based on what I found when looking if this issue could be closed:

Presently, pending 2 PRs, ztunnel consumes John's fork of hyper-util. Pulling the fix from @film42 into ztunnel could occur with a rebase of the branch we consume in John's fork or, after the pending PRs merge, by consuming the upstream again.

**Comment by howardjohn** [comment]
No more todo!() left , closing
