### ISSUE TITLE
Add headless service support

### ISSUE THREAD

**Issue by nmittler** [istio/ztunnel#554]
Ztunnel doesn't currently support headless services. This will be needed by the DNS proxy, however.

The initial DNS proxy PR (#536) ignores headless services for now.

**Comment by hzxuzhonghu** [comment]
Why not supported even without dns proxy?

DNS is resolved by core-dns and ztunnel  fetches Workload(Address) by dst ip

**Comment by nmittler** [comment]
> Why not supported even without dns proxy?

@hzxuzhonghu I'm not sure what your point is here, exactly. If you're just saying that we should implement headless services in ztunnel independent of the DNS proxy work, that's fine. However, DNS proxy is one concrete use case where it's needed.

**Comment by howardjohn** [comment]
I think we can change the proto to stop using VIP and start using service key.

 cc @kdorosh

**Comment by hzxuzhonghu** [comment]
Sorry I mean IIUC ztunnel can send request to headless service currently. For ztunnel there is no much diff,  today ztunnel outbound is based on upstream workload/svc.  And in headless case, definitely it is based on workload.
