### ISSUE TITLE
store all `IpAddr` as Ipv6 in ztunnel

### ISSUE THREAD

**Issue by kdorosh** [istio/ztunnel#582]
cc @nmittler @howardjohn for thoughts on the proposed solution

## Problem

We can get lookup errors in ztunnel if ipv4 addresses are stored in an ipv6 address space. For example, as part of testing https://github.com/istio/istio/pull/45621#discussion_r1245546181 I noticed that the lookups were failing in ztunnel [here](https://github.com/istio/ztunnel/blob/bbe8b3a7f55470fd5804d1f28c6177f29cadc02f/src/proxy/dns.rs#L126-L127) because the `client_addr` in trust_dns had the ipv4 client address stored as an ipv6 space.

For example, a lookup would be made for `::ffff:10.244.2.32` and this would fail to match even though `10.244.2.32` was in the workload store.

One idea I'm having is to use https://doc.rust-lang.org/std/net/struct.Ipv6Addr.html#method.to_ipv4_mapped to put everything in an ipv6 space in ztunnel. Thoughts?

**Comment by kdorosh** [comment]
alternatively i may want to spend more time digging into the trust_dns library to understand why my ipv4 requests are being presented as ipv6-formatted `IpAddr` to the workload store

**Comment by nmittler** [comment]
I'm not sure I see how this is related to Trust-DNS. For a given request, it just returns the appropriate records based on the requested record type (v4/v6).

I suspect the issue is somewhere in the ambient logic (either ztunnel, istiod, or both). IIUC, the client IP of the DNS request is IPv6, but the ztunnel [WorkloadStore](https://github.com/istio/ztunnel/blob/bbe8b3a7f55470fd5804d1f28c6177f29cadc02f/src/state/workload.rs#L487) doesn't have a mapping for that IP? Is my understanding correct?

**Comment by bleggett** [comment]
> I suspect the issue is somewhere in the ambient logic (either ztunnel, istiod, or both). IIUC, the client IP of the DNS request is IPv6, but the ztunnel [WorkloadStore](https://github.com/istio/ztunnel/blob/bbe8b3a7f55470fd5804d1f28c6177f29cadc02f/src/state/workload.rs#L487) doesn't have a mapping for that IP? Is my understanding correct?

Yeah - it's in the WE as IPv4, and it enters lookup as an IPv6-wrapped IPv4 address, so lookup fails.

We still need to decide how to handle IPv6-mapped IPv4 addresses tho, I think.  Ultimately for the DNS lookup we don't have control over what address format the client uses.

Do we actually want the Workload lookup to fail if a client sends an IPv4-in-IPv6 address, and we have a valid Workload with that IPv4 address?

**Comment by nmittler** [comment]
Just backing up for a sec ... Do we know if the Trust-DNS server code is somehow converting the actual client IP to IPv6? If it's not, and the actual client IP is IPv6, wouldn't this be an issue for ambient in general (not just for DNS)?

**Comment by bleggett** [comment]
I think it's just that for the DNS stuff we're not invoking `socket.rs`'s [`to_canonical` ](https://github.com/istio/ztunnel/blob/bbe8b3a7f55470fd5804d1f28c6177f29cadc02f/src/socket.rs#L59) which does do IPv4-in-6 detection.

**Comment by nmittler** [comment]
Ah ok, so is the fix just adding the call to `to_canonical` then?

**Comment by bleggett** [comment]
@nmittler took a stab in https://github.com/istio/ztunnel/pull/585 - this works in that it aligns with existing TCP proxy behavior and fixes @kdorosh's issue, but PTAL.
