### ISSUE TITLE
Need a way to specify ztunnel cluster domain

### ISSUE THREAD

**Issue by nmittler** [istio/ztunnel#587]
The DNS logic uses the domain of the client workload when attempting to expand the request hostname to an FQDN. Currently, the logic just hard-codes the domain to `cluster.local`, but this is may not be valid for the case of custom k8s domains.

Istiod doesn't really support custom domains well today, although this will have to be fixed eventually. In the meantime, we should build in the hook to provide the domain to ztunnel.

As a first-pass, we may just use an environment variable. In the future, however, we might consider providing this value over XDS.

**Comment by hzxuzhonghu** [comment]
not sure what do you mean by istiod not supporting custom dns domain. I can remeber we have such setting

**Comment by nmittler** [comment]
> not sure what do you mean by istiod not supporting custom dns domain. I can remeber we have such setting

Yes, there's a setting, but it's not well tested as a feature and likely is broken.
