### ISSUE TITLE
DNS proxy optimization for entries in DNS cache

### ISSUE THREAD

**Issue by kdorosh** [istio/ztunnel#604]
we can return CNAMEs for hosts we have in our cache to short-path DNS resolution across /etc/resolv.conf resolvers

for context, see https://github.com/istio/ztunnel/pull/599#discussion_r1261387815

this is a potential nice optimization we can bring to ztunnel DNS impl in due time. the implementation would be similar to but not exactly match https://github.com/istio/ztunnel/pull/599, as this PR was returning the CNAME on cache miss rather than cache hit

**Comment by daixiang0** [comment]
Fixed by #603
