### ISSUE TITLE
should encourage using args instead of env 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/ztunnel#606]
compared to env, args is simpler to read even without looking at the source code

**Comment by hzxuzhonghu** [comment]
Yes, i agree config > args > env

**Comment by ilrudie** [comment]
+1 to args being difficult to work with in Kubernetes. Should we rework this issue to be geared towards tracking the proposal and implementation of the config Louis is working on?

**Comment by daixiang0** [comment]
Any update for this?

**Comment by howardjohn** [comment]
The explicit direction from the project overall has to NOT use args anywhere. I am going to close this out to align with that direction.
