### ISSUE TITLE
Benching HBONE handshake performance

### ISSUE THREAD

**Issue by Stevenjin8** [istio/ztunnel#623]
Right now, we have benchmarks for time taken to establish a new TCP connection over an existing HBONE connection because of connection pooling

**Comment by Stevenjin8** [comment]
Thinking of doing this by changing the namespace of the corresponding workload in the workload store via the xds endpoint. Open to new ideas though

**Comment by Stevenjin8** [comment]
It seems like there is a `WorkloadManager` struct as a test helper.

**Comment by Stevenjin8** [comment]
@kdorosh suggest to create a bunch of workloads at the start and then I will have O(n^2) ways to create new HBONE connections. I'll probably do something like take all address in the form `192.0.1.xxx` and then I'll have 65000 ish ways to create new HBONE connections.

**Comment by howardjohn** [comment]
That many workloads may be problematic for scale, is it feasible to add an option to disable pooling? or would that make things too complex? If its too complex then this seems ok, just make sure we don't try >65k executions or we are going to get weird tests results

**Comment by howardjohn** [comment]
Actually opening 65k connections and pooling them may hit OS limits

**Comment by Stevenjin8** [comment]
> Actually opening 65k connections and pooling them may hit OS limits

Definitely agree. 
I was hoping the connection pool would close connections after a certain amount. Another option would be to set the max number of connections to 1 or even 0.

**Comment by Stevenjin8** [comment]
Or maybe doing fewer would suffice. At 20ms per connection, it would only do 250 in 5 seconds. I can also cap the number of times the test runs.

**Comment by howardjohn** [comment]
Good point, forgot its pretty slow anyways. Lets do the simple thing first and if it doesn't work out we can go for more complex options

**Comment by Stevenjin8** [comment]
#631
