### ISSUE TITLE
Random connection resets when accessing a captured workload through a service type LoadBalancer

### ISSUE THREAD

**Issue by keithmattix** [istio/ztunnel#642]
Reproduction steps:
1. Install Istio Ambient (I tested using 1.19-alpha.9080497f9531ce342a6ce67f354fabbe6f5c794a). Installation method should be irrelevant, but for completeness sake, I used the following command:
```shell
TAG=1.19-alpha.9080497f9531ce342a6ce67f354fabbe6f5c794a
HUB=gcr.io/istio-testing
istioctl install --set tag=$TAG --set hub=$HUB --set profile=ambient --set components.ingressGateways[0].enabled=true --set components.ingressGateways[0].name=istio-ingressgateway --skip-confirmation
```
2. Enable ambient capturing in the default namespace: `kubectl label namespace default istio.io/dataplane-mode=ambient`
2. Deploy httpbin from istio/istio: `kubectl apply -f samples/httpbin/httpbin.yaml`
3. Change the httpbin service to a `type: Loadbalancer` with `kubectl edit` (you'll also need to change the service's `port` to 80 instead of 8000)
4. Wait a few seconds for the new External IP to be populated and then run a few curl commands: `curl $EXTERNAL_IP/get`

Every 4th or 5th curl hangs and eventually reports the following error message: `curl: (56) Recv failure: Connection reset by peer`

Kubernetes version was v1.26.6 on AKS

**Comment by keithmattix** [comment]
This is a general issue likely due to some funky iptables things. ztunnel log lines such as `2023-08-14T22:10:45.548306Z  WARN ztunnel::proxy::inbound_passthrough: proxying failed: io error: deadline has elapsed source=192.168.126.1:12118 component="inbound plaintext"` occur every 6 seconds which leads me to believe this is a healthcheck occurring every 5 seconds with a 1 second timeout. Interestingly enough, the source IP as reported by ztunnel corresponds to the istioin interface on the node:

```istioin: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 92:5f:c3:b3:c9:8f brd ff:ff:ff:ff:ff:ff
    inet 192.168.126.1/30 brd 192.168.126.3 scope global istioin
       valid_lft forever preferred_lft forever
    inet6 fe80::dcc8:2fff:fe12:4338/64 scope link
       valid_lft forever preferred_lft forever
```

I'll pick this up eventually if no one else does. @bleggett may find this interesting

**Comment by bleggett** [comment]
(if you have time/this cluster is still up, there's a trick to AKS root access I don't have set up)

can you dump the output of `ip route show` from the node network namespace (e.g. from wherever you ran that `ip addr list`) - I would expect the srcip for a packet coming from outside the cluster to be the srcIP of the host, not the hostside geneve netdev.

**Comment by bleggett** [comment]
All the rules are set up to skip stuff coming from the HostIP (healthchecks, etc) but these are coming from the tunnel entrance IP (which is probably why the packets don't get properly marked/routed and thus dropped on the way out).

I would kinda expect them to come from HostIP, surprised they are not.

**Comment by bleggett** [comment]
This should be retested when inpod hits, I would expect it to not be a problem with that impl, but I've been wrong many times.

**Comment by linsun** [comment]
@jaellio or @keithmattix could you update if you have hit this lately with inpod redirection? Thanks!

**Comment by howardjohn** [comment]
I am almost certain this no longer applies and tested myself
