### ISSUE TITLE
Dynamically setting network isn't supported

### ISSUE THREAD

**Issue by ymesika** [istio/ztunnel#643]
Changing or setting the network **after** installation with the `topology.istio.io/network` label on system namespace breaks DNS and later on fails the upstream connection.

The Ztunnel's DNS server is currently being started with the network from the configuration:

https://github.com/istio/ztunnel/blob/9583efce62c8d9d4c29c987a6479d13803ea8149/src/app.rs#L159

and also when building the request to upstream connection:

https://github.com/istio/ztunnel/blob/a52cbfbd3c16d1698d2bdfbe3da2986707eb83be/src/proxy/outbound.rs#L355

In both places modifying the network as described above will not re-configure the ztunnels and therefore will cause DNS resolution failures and (assuming this is resolved) connection refusal to the upstream ztunnel.

**Comment by stevenctl** [comment]
The namespace label is the last thing checked when determine the network for some endpoint. 

For sidecars this won't get updated until we re-inject.

I wouldn't expect this to be super dynamic for zTunnel, but the fact that it can easily become out of sync with the Pods the zTunnel serves isn't good.

**Comment by ymesika** [comment]
The network is actually being used in the DNS to lookup for the workload in a map where the keys are network+ipaddr.
Assuming we lookup only by ipaddr (either same map or new one) we can get rid of the network there.

The more problematic one is the second lookup later on in the outbound for the downstream workload based on network+addr but this time it also does an on-demand fetch if not found with the network/addr.

**Comment by kdorosh** [comment]
for me, the crux of the issue is a potential race between IP + network updates in control plane and data plane.

(correct me if im missing something) for IP lookups we're reasonably ok because if we don't find the IP we transparently proxy to destination and we can prevent that from happening with L4 / auth policy until the race resolves itself. CNI always acts within the node first so we will always capture new pod traffic so ztunnel can always apply that L4 / auth policy as directed

for network, im a bit more concerned. if ztunnel thinks it has one network while the control plane has another / newer value then ztunnel may send on-demand lookups for IPs and get the wrong xds `Address`. this is more dangerous since we cannot really prevent this with L4 / auth policy until the race is resolved

**Comment by EItanya** [comment]
I agree with @kdorosh here as well. the zTunnel should not need to be aware of its own network, that can lead to the race as described above. If envoy/pilot-agent are aware of the network, I highly doubt that it factors into the data-plane in any meaningful way given that ALL of the envoy routing config is fed from `Istiod` anyway.

**Comment by ymesika** [comment]
Following [comment](https://github.com/istio/ztunnel/issues/643#issuecomment-1668306366) I would like to describe the concrete changes to support it:
* Remove the network configuration from ztunnel. There is no need for it.
* DNS and outbound, when they need to lookup the source workload, will use an empty network (instead of the config network we have today)
* Addresses returned in WDS by istiod will set the network field to empty if the address is on the same network of the ztunnel (and therefore istiod’s). Technically it means modifying the resources just before they are returned by the WDS.
* Addresses of networks other than istiod will be kept untouched
* Comparing against istiod’s network as the ztunnel will no longer have a network (1st bullet). Istiod’s network can be dynamically changed with label.

The main concern with the above is that we need to modify the resources returned in the WDS delta generation and replace the network in addresses of the ztunnel with empty string.

**Comment by ymesika** [comment]
@stevenctl 
> can we do lookups based on the source pod's network?

But how do you know the source pod's network? Ztunnel knows the source pod's IP address and needs to look Workload with network+address. Today we use the static network for this lookup.

**Comment by stevenctl** [comment]
Yes after we talked in the meeting I realized we must know our network to make this work. I'd much rather know our network. dynamic updates makes things nicer; restarting zTunnel isn't horrible (about as bad as sidecars). 

I don't want to change WDS responses based on client info.

**Comment by kdorosh** [comment]
> I don't want to change WDS responses based on client info.

:+1: so long as we have a nice upgrade path from no-network to adopting a network, even with restarts, im happy
