### ISSUE TITLE
When can ztunnel become a production-ready project？

### ISSUE THREAD

**Issue by ghtian123** [istio/ztunnel#668]
What further work is required in the production on the ztunnel? When can the production be used

**Comment by howardjohn** [comment]
https://docs.google.com/document/d/1BLIoPlSOyd4E6QmMAwmLY69_Kf381Fp0iwh1OajLLxs/edit is the tracking doc for driving it to "beta" at which point it will be ready for (cautious) production usage. We are going to turn that all into a github project as well but not ready yet

**Comment by RobCannon** [comment]
@howardjohn , that document mentions Istio 1.20 as the target for a beta release.  I did not see such an announcement in the 1.20 release notes.  Has the target release for ztunnel beta moved to 1.21 or later?

**Comment by howardjohn** [comment]
It will be 1.21 or later.

**Comment by howardjohn** [comment]
Ztunnel will be promoted to beta in Istio 1.22, in ~1 month
