### ISSUE TITLE
When ztunnel tries to respond with `401 Unauthorized`, it terminates connection

### ISSUE THREAD

**Issue by saiskee** [istio/ztunnel#691]
I have the following authorization policy being applied to ztunnel:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: accesspolicy-helloworld-5000-ra-585c83aa589d92115710854631d1f2d
  namespace: helloworld
  resourceVersion: "8507788"
  uid: 28eda17f-e345-42c0-aa70-35de16efc5e5
spec:
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/bookinfo/sa/bookinfo-productpage
    to:
    - operation:
        ports:
        - "5000"
  selector:
    matchLabels:
      app: helloworld
```
When I create a request from the correct service account (bookinfo-productpage), everything works fine. However, when the same request is created from a pod with a diff service account (bookinfo-ratings), I see in the ztunnel logs:
```
2023-09-25T17:36:07.718892Z  WARN proxy{uid=ffc376a2-6bfa-42ad-9e3c-684cdc6b3d54}:outbound{id=9b33a9eb333bb12d3a2bb49178eb24d3}: ztunnel::proxy::outbound: failed dur=8.256389ms err=http status: 401 Unauthorized
```
which means that ztunnel means to send back a 401 response to the client ([code](https://github.com/istio/ztunnel/blob/master/src/proxy/inbound.rs#L296-L300)). However, the client (in this case, curl), gets `Connection reset by peer`:

```
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```
Rather than 401 Unauthorized. Ztunnel seems to be non gracefully terminating the request here.

**Comment by howardjohn** [comment]
This is WAI. The 401 is back to the other ztunnel. We cannot return a 401 to your own application since ztunnel operates at L4 not L7

**Comment by saiskee** [comment]
@howardjohn UX may not match up with waypoint rejecting an unauthorized request, but makes sense so closing for now.

**Comment by howardjohn** [comment]
Yep. For L7 waypoint can be used, which will retain the 401 behavior
