### ISSUE TITLE
Setup ProxyConfig (and other config) reading, and pass this config to various components.

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#7]

**Comment by stevenctl** [comment]
The ProxyConfig should be loaded using the same mechanisms as sidecars:


Environment variable

Annotation

MeshConfig (separate from sidecars)

ProxyConfig CR


Proxy config should be able to set:


Proxy metadata to send to control plane (via ISTIO_META_ env vars)

Concurrency (if configurable

Currently to set the following, we’d need to modify the daemonset or use a webhook:

Image

Actual env vars

**Comment by howardjohn** [comment]
This is pending a design on the user facing experience of configuring. Simply using ProxyConfig requires injection or running in istio-system, neither of which are desirable

**Comment by SkyfireFrancisZ** [comment]
will release PR today

**Comment by howardjohn** [comment]
Done
