### ISSUE TITLE
Implement Hairpinning

### ISSUE THREAD

**Issue by stevenctl** [istio/ztunnel#73]
Traffic sent from outside ambient to a Pod in ambient should use the Waypoint if available.

There are some cases guarded with Skip in existing tests, but that might not be comprehensive.

Example: 
Traffic arrives on the inbound-plaintext port of a uProxy, but the destination is part of an ambient mesh; we should either deny the traffic, or initiate a tunnel. 

For this milestone, we likely just want to deny it. Well-behaved traffic should use proper ingress.

**Comment by SkyfireFrancisZ** [comment]
@linsun @howardjohn do you think this is required for OSS Alpha?

**Comment by howardjohn** [comment]
Yes, we cannot securely implement waypoint proxies without it.

**Comment by linsun** [comment]
Yep what John said.

**Comment by howardjohn** [comment]
Need to make sure we also skip the node fastpath when there is a waypoint.

**Comment by howardjohn** [comment]
Current plan is to implement this for plaintext only and deny HBONE requests instead of hairpinning, with the assumption any HBONE clients are waypoint-aware. We can loosen this restriction, if needed, in the future.

**Comment by SkyfireFrancisZ** [comment]
PR out for review

**Comment by SkyfireFrancisZ** [comment]
waiting on Steven's feedback on the PR

**Comment by SkyfireFrancisZ** [comment]
code merged. waiting on testing PR

**Comment by howardjohn** [comment]
Just need https://github.com/istio/ztunnel/pull/348
