### ISSUE TITLE
Support custom SECRET_TTL and SECRET_GRACE_PERIOD_RATIO in ztunnel

### ISSUE THREAD

**Issue by GregHanson** [istio/ztunnel#736]
ztunnel currently has `SECRET_TTL` hardcoded to 24 hours [here](https://github.com/istio/ztunnel/blob/master/src/identity/caclient.rs#L68) and `SECRET_GRACE_PERIOD_RATIO` hardcoded to 0.5 [here](https://github.com/istio/ztunnel/blob/master/src/tls/boring.rs#L187).  Sidecar supports these two environment variables to allow customizing these cert rotations settings - should ztunnel do the same?

**Comment by GregHanson** [comment]
related to second item raised during review [here](https://github.com/istio/ztunnel/pull/730#issuecomment-1821649547)

> Eventually you do need to mint certificates with 'new'. Is 12hr short enough for this, or do we need something between "instant" and "12hr"? 12hr seems fine to me... plus you can always force it w/ restart

In addition to the two env vars, sidecar also has PCDS as a way to pick up some cert changes immediately.  Since ztunnel does not support PCDS, these env vars would allow users who don't want to wait up to 12 hours for cert changes to have some control over these settings

**Comment by hzxuzhonghu** [comment]
To support multi root tust and root cert rotation,  I think PCDS should be supported.

It is simple to add two environments to ztunnel.

**Comment by hzxuzhonghu** [comment]
@linsun PCDS response now only contains cacerts. Logging level can be changed by `istioctl proxy-config log <sidecar-pod> <sidecar-container> --level <log-level>` now.

**Comment by linsun** [comment]
> @linsun PCDS response now only contains cacerts. Logging level can be changed by `istioctl proxy-config log <sidecar-pod> <sidecar-container> --level <log-level>` now.

Do you mean this cmd is also avail for ztunnel as well?

**Comment by GregHanson** [comment]
@linsun best way to use the log command for ztunnel is:
```
istioctl pc log ds/ztunnel -n istio-system --level <error|warn|info|debug|trace>
```
which will configure all ztunnels at once

**Comment by GregHanson** [comment]
> It is simple to add two environments to ztunnel.

@hzxuzhonghu outside of meshconfig settings (in src/config.rs), there isn't much precedence for pulling in configuration settings from environment variables.  Couldn't recall if there was any intentional design discussion around this or if it was just something that was saved for post-beta

**Comment by GregHanson** [comment]
`SECRET_TTL` support is merged via https://github.com/istio/ztunnel/pull/742.  Exposing one of `SECRET_TTL` or `SECRET_GRACE_PERIOD_RATIO` is probably sufficient for most use cases
