### ISSUE TITLE
Pooling key needs to take source IP

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#770]
https://github.com/istio/ztunnel/blob/d867379ffa457153034d0d6c911810453caa8505/src/proxy/pool.rs#L85-L91

No src pod here. So if you send request from 2 pods on the same node to some destination pod, the destination will see them as from the same src IP incorrectly

**Comment by ilrudie** [comment]
Would this be a Beta blocker? Seems like it's not a security issue but more a bug that'll make telemetry and troubleshooting weird.

**Comment by ilrudie** [comment]
(also, do you have code for this John? If not and we think it'll block Beta I'd be happy to add it to my up next)

**Comment by howardjohn** [comment]
I forgot to mention it mostly/entirely doesn't matter for inpod. So that may be the only "Beta" part anyways. But ignoring that I would say yes. The fix should be pretty simple ,though. We should make sure `src` is not `SocketAddr`  but `IpAddr`.

> (also, do you have code for this John? If not and we think it'll block Beta I'd be happy to add it to my up next)


I haven't worked on this yet, just noticed with @srampal  and tested to confirm its broken

**Comment by ilrudie** [comment]
yeah, fair point re: inpod. I agree the fix doesn't seem like it would be difficult

**Comment by srampal** [comment]
@howardjohn @ilrudie If you arent working on this, I could potentially work on this as it seems a relatively simple fix for someone new to the code to get experience making a code fix. Plus its an area I've been looking into.

**Comment by hzxuzhonghu** [comment]
@howardjohn Can you clarify why cannot we share connection per {src-dst} identity?

**Comment by ilrudie** [comment]
@srampal, go for it. I had not begun any work on this

**Comment by hzxuzhonghu** [comment]
OK, I get sharing connection per identify could be wrong in some case. But if not possible or share per IP,  i donot think the connection pool is as useful as now.

**Comment by ilrudie** [comment]
I don't think this really changes the value of pooling connections much. From my understanding this only really happens when 2 or more source pods sharing an identity exist on the same node and the fix would be basically the same as if those 2 pods happened to be on different nodes in terms of pool efficiency. That still seems fine to me.
