### ISSUE TITLE
Tracking issue: Upgrade tonic to hyper 1.0 support

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#796]
Tracking issue to get off forks.

We currently need a compat shim, which we have a fork of: https://github.com/davidpdrsn/tower-hyper-http-body-compat/pull/7. Worst case, we should get that merged so we are off forks.

best case, tonic adopts 1.0 so we do not need a shim at all: https://github.com/hyperium/tonic/issues/1307

**Comment by daixiang0** [comment]
Is fixed by #726?

**Comment by howardjohn** [comment]
No, we have a shim for tonic because its missing 1.0 support. Blocked on https://github.com/hyperium/tonic/issues/1307

**Comment by howardjohn** [comment]
this is done

```
$ cargo tree | rg hyper
├── hyper v1.4.1
├── hyper-rustls v0.27.2
│   ├── hyper v1.4.1 (*)
│   ├── hyper-util v0.1.7
│   │   ├── hyper v1.4.1 (*)
├── hyper-util v0.1.7 (*)
```
