### ISSUE TITLE
add cargo watch or bacon to build tools

### ISSUE THREAD

**Issue by ilrudie** [istio/ztunnel#808]
This is to build consensus about adding [cargo watch](https://crates.io/crates/cargo-watch) or [bacon](https://crates.io/crates/bacon) to our build tools image.

I personally like to work inside of `make shell` when possible for consistency. I also like using cargo watch and/or bacon to track changes and re-test/re-lint/rebuild automatically.

Upsides:

- handy
- easy to get with native rust tooling `cargo install cargo-watch` or `cargo install --locked bacon`

Downsides:

- not strictly required for builds, possibly out of scope as a result
- building native rust tooling like this takes time
- adds ~5mb (bacon) or ~7mb (cargo-watch) to image

**Comment by howardjohn** [comment]
Can you just install in a volume that is mounted via CONDITIONAL_HOST_MOUNTS? Then you can install the kitchen sink of whatever you want?

**Comment by ilrudie** [comment]
That's fair. Adding it into the image is not the only way
