### ISSUE TITLE
Allow providing static YAML config

### ISSUE THREAD

**Issue by stevenctl** [istio/ztunnel#81]
Command line flags can be provided as part of “bootstrap” config (flags still take precedence)

Any xDS objects can be specified here

It can be used in conjunction with xDS

**Comment by stevenctl** [comment]
We already have a way to add a static yaml with "Workloads". 

We should standardize on some format that allows arbitrary xDS types.

**Comment by GregHanson** [comment]
@stevenctl assuming this should be included in the ztunnnel `/config_dump` API tracked here?
https://github.com/istio/ztunnel/issues/87

**Comment by howardjohn** [comment]
This is done now, all types can be used
