### ISSUE TITLE
Developer-Facing Simple Counters

### ISSUE THREAD

**Issue by stevenctl** [istio/ztunnel#85]
Can be cheaply incremented (no locking, etc). Used
primarily for devs to see how many times some
codepath is hit. Not “prometheus-y” metrics (e.g.
byte counts, etc)

It should be incredibly easy to create a counter in the code and update it.
* Number that can be incremented cheaply at runtime.
* istioctl should include a tool that shows value of all counters. Should also show the rate of change.
* It should not be possible to disable counters, these aren't like log levels, they should be on all the time.
* Debug tool should dump the current value of all counters.
* Should be able to watch counters.
* Counters should include other major events
  * Errors
  * Cleanup work or other debugging stuff.
  * Control Plane Changes

**Comment by ilrudie** [comment]
@stevenctl, Is the doc you mentioned above public? If so would it be possible to link to the doc?

**Comment by linsun** [comment]
> Can be cheaply incremented (no locking, etc). Used primarily for devs to see how many times some codepath is hit. Not “prometheus-y” metrics (e.g. byte counts, etc)
> 
> Described in Ethan’s doc.

@howardjohn @ejj @stevenctl can you pls share the doc?

**Comment by stevenctl** [comment]
Ah, the doc was sort of a brainstorming list of tasks, forgot to copy/paste some things before importing to github. Updated the description with text directly from said doc.

**Comment by ilrudie** [comment]
Thanks for the info @stevenctl. I will take a look at this extra detail and work on a proposal.
