### ISSUE TITLE
idemepotency_add_workload_fails test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#888]
https://prow.istio.io/view/gs/istio-prow/logs/test_ztunnel_postsubmit/1776030111359832064

```
thread 'inpod::statemanager::tests::idemepotency_add_workload_fails' panicked at src/inpod/statemanager.rs:434:9:
assertion failed: !state.have_pending()
```

Locally: 
```
287362 runs so far, 0 failures (100.00% pass rate). 4.54875ms avg, 47.098639ms max, 2.663018ms min
```

so it must be pretty obscure...

**Comment by MorrisLaw** [comment]
Investigating another flake in [logs/test_ztunnel_postsubmit](https://prow.istio.io/job-history/gs/istio-prow/logs/test_ztunnel_postsubmit) and came across a recent version of this particular flake. Sharing it here as another more recent data point for whoever picks this up: https://prow.istio.io/view/gs/istio-prow/logs/test_ztunnel_postsubmit/1782869865959264256

**Comment by howardjohn** [comment]
oof the test wasn't running locally since requires root
