### ISSUE TITLE
Audit .unwrap and .expect usages; replace with proper error handling where needed.

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#9]

**Comment by yuval-k** [comment]
to that end, clippy can help `cargo clippy -- -D clippy::expect_used -D clippy::panic -D clippy::unwrap_used`

**Comment by SkyfireFrancisZ** [comment]
started working on the PR

**Comment by howardjohn** [comment]
Move to https://github.com/istio/ztunnel/issues/1245
