### ISSUE TITLE
test_vip_request test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#917]
https://prow.istio.io/view/gs/istio-prow/logs/test_ztunnel_postsubmit/1778535127471624192#1:build-log.txt%3A1759

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/test_ztunnel_postsubmit/1779908701956608000

**Comment by MorrisLaw** [comment]
Is there a way to easily see the frequency of this flake as it occurs in the CI? (e.g. how many flakes every N runs). 

According to the stack trace, this failing [line](https://github.com/istio/ztunnel/blob/69f07920510a4962519f4c6b3ad3e9f5f7339e94/tests/namespaced.rs#L721):
```rust
stream.read_exact(&mut buf).await.unwrap();
```

seems to be related to the chance of flake described [here](https://github.com/istio/ztunnel/blob/69f07920510a4962519f4c6b3ad3e9f5f7339e94/tests/namespaced.rs#L203).
```rust
// run 15 requests so chance of flake here is 1/2^15 = ~0.003%
run_tcp_client_iters(lb_client, 15, manager.resolver(), &format!("{TEST_VIP}:80"))?;
```

Wonder if it makes sense to decrease the chance to ~0.00009% by running it 20 times. Or maybe we should just fix the flake altogether, but this comment leads to me believe it's not straightforward? Do you know any additional context about this comment?

**Comment by MorrisLaw** [comment]
Nvm, job history shows a significant amount of failures than the chance described in that comment, 4 out of 20! https://prow.istio.io/job-history/gs/istio-prow/logs/test_ztunnel_postsubmit

**Comment by howardjohn** [comment]
This test was actually removed/replaced (now basically service_loadbalancing). As part of that replacement, the new test seems to be full reliable.

**Comment by howardjohn** [comment]
`209 runs so far, 0 failures (100.00% pass rate). 3.10638293s avg, 3.939583567s max, 1.017441112s min`
