### ISSUE TITLE
DOC: run ztunnel in kind not works

### ISSUE THREAD

**Issue by yanickxia** [istio/ztunnel#934]
from this mr https://github.com/istio/ztunnel/pull/820 merge, seem debug in kind is break.

when start, logs as
```bash
2024-04-17T03:12:20.744145Z     warn    xds::client:xds{id=9}   XDS client connection error: gRPC connection error:status: Unknown, message: "client error (Connect)", source: invalid peer certificate: NotValidForName, retrying in 5.12s      
```

seem [server_verifier](https://github.com/rustls/rustls/blob/d2e1e668aae3d9807ffa782ea29ed26f2778371d/rustls/src/webpki/server_verifier.rs#L256) will check DNS Subject_names,  not include 'localhost'
```rust
verify_server_name(&cert, server_name)?;
Ok(ServerCertVerified::assertion())
```

Temporary solution

```bash
echo "127.0.0.1 istiod.istio-system.svc" >> /etc/hosts
```

when start add two env

```bash
CA_ADDRESS=https://istiod.istio-system.svc:15012
XDS_ADDRESS=https://istiod.istio-system.svc:15012
```

---

Maybe we should add some reminders to the document. seem not good way to support this case....

**Comment by howardjohn** [comment]
ISTIOD_CUSTOM_HOST=localhost on istiod also works
