### ISSUE TITLE
Automated E2E Performance Tests

### ISSUE THREAD

**Issue by stevenctl** [istio/ztunnel#98]
Clear instructions on how to run

Primarily target GKE, instructions include cluster/node sizing.

Tools/scripts are part of istio/tools. 

There is a well-known location to publish and compare results.

Targeting iperf, nighthawk, netperf tcp crr, fairness (measure tbd)

Measure resource usage (CPU, RAM)

Can/should we integrate into perf/benchmark?

**Comment by stevenctl** [comment]
I think I heard someone was adding something to our release verification, is that right?

**Comment by howardjohn** [comment]
Deduping with https://github.com/istio/ztunnel/issues/214 (which has some more comments)
