### ISSUE TITLE
Isolated (non-k8s) performance tests

### ISSUE THREAD

**Issue by stevenctl** [istio/ztunnel#99]
Clear instructions on how to run

There is a well-known location to publish and compare results.

Targeting iperf, nighthawk, netperf tcp crr, fairness (measure tbd)

Measure resource usage (CPU, RAM)

These tests may be the same as the E2E ones, but can easily be run either 1 or 2 machines with only the testing infra and the zTunnel.

**Comment by howardjohn** [comment]
I ran it adhoc, I think we want to make it trivial to run (e.g `cargo bench --test throughput`) or whatever

**Comment by linsun** [comment]
Has a open PR for it, should be done soon.
